#!/usr/bin/env bash
#
# DNS Tunnel Server Manager
# All-in-one setup, management, and monitoring for DNSTT DNS tunnels
# Optimized for heavily censored networks (DoH/DoT/UDP)
#
# Tested on: Ubuntu 20.04 / 22.04 / 24.04
#
# Usage:
#   sudo bash dns-tunnel-server.sh          # Interactive menu
#   sudo bash dns-tunnel-server.sh setup    # Run setup wizard directly
#   sudo bash dns-tunnel-server.sh status   # Quick status check
#

set -uo pipefail

# ─── Constants ────────────────────────────────────────────────────────────────

SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="dns-tunnel-server"
DNSTT_BINARY="/usr/local/bin/dnstt-server"
DNSTT_CLIENT_URL="https://dnstt.network"
DNSTT_BASE_URL="https://dnstt.network"
CONFIG_DIR="/etc/dnstt"
CONFIG_FILE="$CONFIG_DIR/tunnel.conf"
SYSTEMD_SERVICE="dnstt-server"
SYSTEMD_DIR="/etc/systemd/system"
SERVICE_FILE="$SYSTEMD_DIR/${SYSTEMD_SERVICE}.service"
DANTE_SERVICE="danted"
DANTE_CONF="/etc/danted.conf"
DNSTT_USER="dnstt"
DNSTT_PORT="5300"
LOG_FILE="/var/log/dnstt-server.log"

# ─── Colors ───────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

# ─── Utility Functions ────────────────────────────────────────────────────────

print_line() {
    printf '%*s\n' "${1:-60}" '' | tr ' ' "${2:-─}"
}

print_header() {
    local width=60
    echo ""
    echo -e "${CYAN}"
    print_line $width "═"
    printf "  %s\n" "$1"
    if [[ -n "${2:-}" ]]; then
        printf "  ${DIM}%s${NC}${CYAN}\n" "$2"
    fi
    print_line $width "═"
    echo -e "${NC}"
}

print_section() {
    echo ""
    echo -e "  ${BOLD}${BLUE}▸ $1${NC}"
    print_line 60 "─"
}

print_ok() {
    echo -e "  ${GREEN}✓${NC} $1"
}

print_err() {
    echo -e "  ${RED}✗${NC} $1"
}

print_warn() {
    echo -e "  ${YELLOW}!${NC} $1"
}

print_info() {
    echo -e "  ${CYAN}ℹ${NC} $1"
}

print_dim() {
    echo -e "  ${DIM}$1${NC}"
}

press_enter() {
    echo ""
    read -rp "  Press Enter to continue..." _
}

confirm() {
    local msg="${1:-Continue?}"
    read -rp "  $msg [Y/n]: " ans
    [[ -z "$ans" || "$ans" =~ ^[Yy] ]]
}

# ─── Detection Functions ─────────────────────────────────────────────────────

detect_os() {
    if [[ ! -f /etc/os-release ]]; then
        print_err "Cannot detect OS"
        return 1
    fi
    . /etc/os-release
    echo "$ID"
}

detect_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        armv7l|armhf)  echo "arm" ;;
        i686|i386)     echo "386" ;;
        *)             echo "amd64" ;;
    esac
}

detect_server_ip() {
    local ip
    ip=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null) ||
    ip=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null) ||
    ip=$(curl -s --max-time 5 https://icanhazip.com 2>/dev/null) ||
    ip=$(hostname -I 2>/dev/null | awk '{print $1}') ||
    ip="(unknown)"
    echo "$ip"
}

detect_ssh_port() {
    local port
    port=$(ss -tlnp 2>/dev/null | grep sshd | head -1 | grep -oP ':\K[0-9]+' | head -1)
    echo "${port:-22}"
}

detect_main_interface() {
    ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1
}

is_installed() {
    [[ -f "$DNSTT_BINARY" ]]
}

is_configured() {
    [[ -f "$CONFIG_FILE" ]]
}

is_running() {
    systemctl is-active --quiet "$SYSTEMD_SERVICE" 2>/dev/null
}

get_config_value() {
    local key="$1"
    if [[ -f "$CONFIG_FILE" ]]; then
        grep "^${key}=" "$CONFIG_FILE" 2>/dev/null | cut -d'=' -f2-
    fi
}

# ─── Load Config ──────────────────────────────────────────────────────────────

load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        CONF_DOMAIN=$(get_config_value "DOMAIN")
        CONF_MTU=$(get_config_value "MTU")
        CONF_MODE=$(get_config_value "MODE")
        CONF_SSH_PORT=$(get_config_value "SSH_PORT")
        CONF_PUBKEY=$(get_config_value "PUBKEY")
        CONF_PRIVKEY_FILE=$(get_config_value "PRIVKEY_FILE")
        CONF_PUBKEY_FILE=$(get_config_value "PUBKEY_FILE")
        CONF_SERVER_IP=$(get_config_value "SERVER_IP")
        CONF_SOCKS_USER=$(get_config_value "SOCKS_USER")
        CONF_SOCKS_PASS=$(get_config_value "SOCKS_PASS")
        return 0
    fi
    return 1
}

save_config() {
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" << EOF
# DNS Tunnel Server Configuration
# Generated by $SCRIPT_NAME v$SCRIPT_VERSION
# $(date)
DOMAIN=$CONF_DOMAIN
MTU=$CONF_MTU
MODE=$CONF_MODE
SSH_PORT=$CONF_SSH_PORT
PUBKEY=$CONF_PUBKEY
PRIVKEY_FILE=$CONF_PRIVKEY_FILE
PUBKEY_FILE=$CONF_PUBKEY_FILE
SERVER_IP=$CONF_SERVER_IP
SOCKS_USER=${CONF_SOCKS_USER:-}
SOCKS_PASS=${CONF_SOCKS_PASS:-}
EOF
    chmod 600 "$CONFIG_FILE"
}

# ─── Installation Functions ───────────────────────────────────────────────────

install_dependencies() {
    print_section "Installing Dependencies"

    local packages=(curl wget iptables)
    local to_install=()

    for pkg in "${packages[@]}"; do
        if ! command -v "$pkg" &>/dev/null; then
            to_install+=("$pkg")
        fi
    done

    if [[ ${#to_install[@]} -gt 0 ]]; then
        print_info "Installing: ${to_install[*]}"
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y -qq "${to_install[@]}" >/dev/null 2>&1
        print_ok "Dependencies installed"
    else
        print_ok "All dependencies present"
    fi
}

download_dnstt_binary() {
    print_section "Downloading DNSTT Server Binary"

    local arch
    arch=$(detect_arch)
    local binary_name="dnstt-server-linux-${arch}"
    local url="${DNSTT_BASE_URL}/${binary_name}"

    print_info "Architecture: $arch"
    print_info "Downloading from: $url"

    local tmp_file="/tmp/${binary_name}"
    if ! curl -fsSL --connect-timeout 30 "$url" -o "$tmp_file"; then
        print_err "Failed to download dnstt-server"
        print_info "Try manually: curl -fsSL $url -o $DNSTT_BINARY"
        return 1
    fi

    chmod +x "$tmp_file"
    mv "$tmp_file" "$DNSTT_BINARY"
    print_ok "Binary installed: $DNSTT_BINARY"

    # Verify
    if "$DNSTT_BINARY" -h >/dev/null 2>&1 || [[ -x "$DNSTT_BINARY" ]]; then
        print_ok "Binary is executable"
    else
        print_err "Binary may not be working"
    fi
}

create_system_user() {
    if id "$DNSTT_USER" &>/dev/null; then
        print_ok "System user '$DNSTT_USER' already exists"
        return 0
    fi
    useradd -r -s /usr/sbin/nologin -d /nonexistent "$DNSTT_USER" 2>/dev/null
    print_ok "Created system user: $DNSTT_USER"
}

generate_keys() {
    print_section "Generating Encryption Keys"

    local domain_file
    domain_file=$(echo "$CONF_DOMAIN" | tr '.' '_')
    CONF_PRIVKEY_FILE="${CONFIG_DIR}/${domain_file}_server.key"
    CONF_PUBKEY_FILE="${CONFIG_DIR}/${domain_file}_server.pub"

    mkdir -p "$CONFIG_DIR"

    # Check for existing keys
    if [[ -f "$CONF_PRIVKEY_FILE" && -f "$CONF_PUBKEY_FILE" ]]; then
        print_info "Keys already exist for this domain"
        if confirm "Reuse existing keys?"; then
            CONF_PUBKEY=$(cat "$CONF_PUBKEY_FILE")
            print_ok "Reusing keys: $CONF_PUBKEY_FILE"
            return 0
        fi
    fi

    # Generate new keys
    print_info "Generating Curve25519 key pair..."
    "$DNSTT_BINARY" -gen-key -privkey-file "$CONF_PRIVKEY_FILE" -pubkey-file "$CONF_PUBKEY_FILE" 2>/dev/null

    if [[ ! -f "$CONF_PUBKEY_FILE" ]]; then
        print_err "Key generation failed"
        return 1
    fi

    CONF_PUBKEY=$(cat "$CONF_PUBKEY_FILE")
    chown "$DNSTT_USER":"$DNSTT_USER" "$CONF_PRIVKEY_FILE" 2>/dev/null
    chmod 600 "$CONF_PRIVKEY_FILE"

    print_ok "Private key: $CONF_PRIVKEY_FILE"
    print_ok "Public key:  $CONF_PUBKEY_FILE"
    print_info "Public key value: ${CYAN}$CONF_PUBKEY${NC}"
}

setup_iptables() {
    print_section "Configuring Firewall (iptables)"

    # Redirect port 53 to dnstt port
    local rules_needed=false

    if ! iptables -t nat -C PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null; then
        iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT"
        rules_needed=true
    fi
    if ! iptables -t nat -C PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null; then
        iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT"
        rules_needed=true
    fi

    # Allow port 53 in INPUT
    if ! iptables -C INPUT -p udp --dport 53 -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p udp --dport 53 -j ACCEPT
    fi
    if ! iptables -C INPUT -p tcp --dport 53 -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p tcp --dport 53 -j ACCEPT
    fi

    # Also allow the dnstt port directly
    if ! iptables -C INPUT -p udp --dport "$DNSTT_PORT" -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p udp --dport "$DNSTT_PORT" -j ACCEPT
    fi

    # UFW rules
    if command -v ufw &>/dev/null; then
        ufw allow 53/udp >/dev/null 2>&1
        ufw allow 53/tcp >/dev/null 2>&1
        ufw allow "$DNSTT_PORT"/udp >/dev/null 2>&1
        print_ok "UFW rules added for port 53 and $DNSTT_PORT"
    fi

    # Save iptables rules persistently
    if command -v netfilter-persistent &>/dev/null; then
        netfilter-persistent save >/dev/null 2>&1
    elif [[ -f /etc/iptables/rules.v4 ]]; then
        iptables-save > /etc/iptables/rules.v4 2>/dev/null
    fi

    print_ok "iptables rules configured (53 → $DNSTT_PORT)"
}

free_port_53() {
    print_section "Freeing Port 53"

    local port53_user
    port53_user=$(ss -ulnp 2>/dev/null | grep ':53 ' | head -1)

    if [[ -z "$port53_user" ]]; then
        print_ok "Port 53 is free"
        return 0
    fi

    print_warn "Port 53 is in use:"
    print_dim "$port53_user"

    # Check if it's systemd-resolved
    if echo "$port53_user" | grep -q "systemd-resolve\|resolved"; then
        print_info "systemd-resolved is using port 53. Disabling..."

        systemctl stop systemd-resolved.socket systemd-resolved.service 2>/dev/null
        systemctl disable systemd-resolved.socket systemd-resolved.service 2>/dev/null
        systemctl mask systemd-resolved.socket systemd-resolved.service 2>/dev/null

        # Fix resolv.conf
        chattr -i /etc/resolv.conf 2>/dev/null
        rm -f /etc/resolv.conf
        cat > /etc/resolv.conf << 'EOF'
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 9.9.9.9
EOF
        chattr +i /etc/resolv.conf 2>/dev/null

        print_ok "systemd-resolved disabled"
        print_ok "DNS set to 8.8.8.8, 1.1.1.1, 9.9.9.9"
    else
        print_warn "Unknown service on port 53. You may need to stop it manually."
        print_dim "Run: ss -ulnp | grep ':53 '"
        if ! confirm "Continue anyway?"; then
            return 1
        fi
    fi

    # Verify
    sleep 1
    if ss -ulnp 2>/dev/null | grep -q ':53 '; then
        print_err "Port 53 still in use!"
        pkill -9 systemd-resolve 2>/dev/null
        sleep 1
        if ss -ulnp 2>/dev/null | grep -q ':53 '; then
            print_err "Cannot free port 53. Please fix manually."
            return 1
        fi
    fi

    print_ok "Port 53 is now free"
}

install_dante_socks() {
    print_section "Installing Dante SOCKS5 Proxy"

    if command -v danted &>/dev/null; then
        print_ok "Dante already installed"
    else
        print_info "Installing dante-server..."
        apt-get install -y -qq dante-server >/dev/null 2>&1
        if ! command -v danted &>/dev/null; then
            print_err "Failed to install dante-server"
            print_info "Trying alternative: apt install dante-server"
            apt-get install -y dante-server 2>&1
        fi
    fi

    local iface
    iface=$(detect_main_interface)

    cat > "$DANTE_CONF" << EOF
# Dante SOCKS5 proxy for DNSTT tunnel
logoutput: syslog

internal: 127.0.0.1 port = 1080

external: $iface

socksmethod: username
clientmethod: none

user.privileged: root
user.notprivileged: nobody

client pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
    log: error
}

socks pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
    command: bind connect udpassociate
    log: error
    socksmethod: username
}
EOF

    systemctl enable "$DANTE_SERVICE" >/dev/null 2>&1
    systemctl restart "$DANTE_SERVICE" >/dev/null 2>&1

    if systemctl is-active --quiet "$DANTE_SERVICE"; then
        print_ok "Dante SOCKS5 running on 127.0.0.1:1080"
    else
        print_warn "Dante may not have started. Check: systemctl status danted"
    fi
}

create_socks_user() {
    print_section "Creating SOCKS Tunnel User"

    local default_user="tunnel"
    read -rp "  Username [$default_user]: " CONF_SOCKS_USER
    CONF_SOCKS_USER="${CONF_SOCKS_USER:-$default_user}"

    # Generate random password
    local rand_pass
    rand_pass=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 12)
    read -rp "  Password [$rand_pass]: " CONF_SOCKS_PASS
    CONF_SOCKS_PASS="${CONF_SOCKS_PASS:-$rand_pass}"

    # Create or update user
    if id "$CONF_SOCKS_USER" &>/dev/null; then
        print_info "User '$CONF_SOCKS_USER' exists, updating password..."
    else
        useradd -r -s /usr/sbin/nologin "$CONF_SOCKS_USER" 2>/dev/null ||
        useradd -r -s /bin/false "$CONF_SOCKS_USER" 2>/dev/null
    fi

    echo "${CONF_SOCKS_USER}:${CONF_SOCKS_PASS}" | chpasswd

    print_ok "User: $CONF_SOCKS_USER"
    print_ok "Pass: $CONF_SOCKS_PASS"
}

create_systemd_service() {
    print_section "Creating Systemd Service"

    local listen_addr="127.0.0.1:${DNSTT_PORT}"
    local forward_addr=""

    if [[ "$CONF_MODE" == "socks" ]]; then
        forward_addr="127.0.0.1:1080"
    else
        forward_addr="127.0.0.1:${CONF_SSH_PORT}"
    fi

    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=DNSTT DNS Tunnel Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$DNSTT_USER
Group=$DNSTT_USER
ExecStart=$DNSTT_BINARY \\
    -udp $listen_addr \\
    -privkey-file $CONF_PRIVKEY_FILE \\
    -mtu $CONF_MTU \\
    $CONF_DOMAIN \\
    $forward_addr
Restart=always
RestartSec=5
LimitNOFILE=65535

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadOnlyPaths=/
ReadWritePaths=/var/log
PrivateTmp=yes

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=dnstt-server

[Install]
WantedBy=multi-user.target
EOF

    # dnstt user needs read access to private key
    chown "$DNSTT_USER":"$DNSTT_USER" "$CONF_PRIVKEY_FILE" 2>/dev/null

    systemctl daemon-reload
    systemctl enable "$SYSTEMD_SERVICE" >/dev/null 2>&1

    print_ok "Service created: $SERVICE_FILE"
    print_ok "Forwarding to: $forward_addr"
}

# ─── Setup Wizard ─────────────────────────────────────────────────────────────

run_setup() {
    print_header "DNS Tunnel Server Setup Wizard" "Step-by-step guided installation"

    local total_steps=9
    local step=0

    # ── Step 1: Pre-flight ────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Pre-flight Checks"

    # Root check
    if [[ $EUID -ne 0 ]]; then
        print_err "Must run as root (sudo)"
        exit 1
    fi
    print_ok "Running as root"

    # OS check
    local os
    os=$(detect_os)
    if [[ "$os" != "ubuntu" && "$os" != "debian" ]]; then
        print_warn "OS '$os' detected. This script is tested on Ubuntu/Debian."
        if ! confirm "Continue anyway?"; then exit 0; fi
    else
        print_ok "OS: $os"
    fi

    # Detect IP
    CONF_SERVER_IP=$(detect_server_ip)
    print_ok "Server IP: $CONF_SERVER_IP"

    # Detect SSH
    CONF_SSH_PORT=$(detect_ssh_port)
    print_ok "SSH port: $CONF_SSH_PORT"

    # ── Step 2: Domain ────────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Domain Configuration"

    echo ""
    print_info "Enter the tunnel subdomain (not the base domain)"
    print_info "Example: ${CYAN}t.example.com${NC}"
    print_dim "You need an NS record pointing this subdomain to your server"
    echo ""

    local existing_domain=""
    if is_configured; then
        load_config
        existing_domain="$CONF_DOMAIN"
        print_info "Current domain: $existing_domain"
    fi

    read -rp "  Tunnel domain [${existing_domain:-t.example.com}]: " CONF_DOMAIN
    CONF_DOMAIN="${CONF_DOMAIN:-${existing_domain:-t.example.com}}"

    # Strip whitespace, protocol prefixes
    CONF_DOMAIN=$(echo "$CONF_DOMAIN" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s|^https\?://||;s|/$||')
    print_ok "Domain: $CONF_DOMAIN"

    # ── Step 3: DNS Records ───────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — DNS Records"

    local base_domain tunnel_sub ns_hostname
    # Extract parts
    base_domain=$(echo "$CONF_DOMAIN" | rev | cut -d. -f1-2 | rev)
    tunnel_sub=$(echo "$CONF_DOMAIN" | sed "s/\.$base_domain$//")
    ns_hostname="ns.$base_domain"

    echo ""
    echo -e "  ${BOLD}Create these DNS records in your registrar/Cloudflare:${NC}"
    echo ""
    echo -e "  ┌────────┬──────────────────────┬───────────────────────────┐"
    echo -e "  │ ${BOLD}Type${NC}   │ ${BOLD}Name${NC}                 │ ${BOLD}Value${NC}                     │"
    echo -e "  ├────────┼──────────────────────┼───────────────────────────┤"
    printf "  │ A      │ %-20s │ %-25s │\n" "ns" "$CONF_SERVER_IP"
    printf "  │ NS     │ %-20s │ %-25s │\n" "$tunnel_sub" "$ns_hostname"
    echo -e "  └────────┴──────────────────────┴───────────────────────────┘"
    echo ""
    print_warn "A record proxy must be OFF (grey cloud) if using Cloudflare"
    print_info "Wait 5-10 min for DNS propagation after creating records"
    echo ""

    if ! confirm "Have you created these DNS records?"; then
        print_warn "Create the records first, then re-run this setup"
        exit 0
    fi

    # ── Step 4: Tunnel Mode ───────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Tunnel Mode"

    echo ""
    echo -e "  ${BOLD}1)${NC} SOCKS proxy mode"
    print_dim "   Anyone with the domain + key can connect"
    print_dim "   Simpler setup, no passwords needed"
    echo ""
    echo -e "  ${BOLD}2)${NC} SSH tunnel mode"
    print_dim "   Requires username + password"
    print_dim "   Better access control, per-user auth"
    print_dim "   Compatible with mobile apps"
    echo ""

    read -rp "  Choose mode [1]: " mode_choice
    mode_choice="${mode_choice:-1}"

    if [[ "$mode_choice" == "2" ]]; then
        CONF_MODE="ssh"
        print_ok "Mode: SSH tunnel"
    else
        CONF_MODE="socks"
        print_ok "Mode: SOCKS proxy"
    fi

    # ── Step 5: MTU ───────────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — MTU Configuration"

    echo ""
    echo -e "  ${BOLD}MTU recommendations for censored networks:${NC}"
    echo ""
    echo -e "    ${GREEN}512${NC}  — Maximum compatibility (heavy censorship)"
    echo -e "    ${YELLOW}800${NC}  — Balanced"
    echo -e "    ${CYAN}1024${NC} — Faster, moderate censorship"
    echo -e "    1232 — Default (may not work under heavy filtering)"
    echo ""

    read -rp "  MTU [512]: " CONF_MTU
    CONF_MTU="${CONF_MTU:-512}"

    # Validate
    if [[ "$CONF_MTU" -lt 200 || "$CONF_MTU" -gt 1400 ]] 2>/dev/null; then
        print_warn "MTU must be 200-1400. Using 512."
        CONF_MTU=512
    fi
    print_ok "MTU: $CONF_MTU"

    # ── Step 6: Install ──────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Installing Components"

    install_dependencies
    free_port_53
    create_system_user

    if [[ -f "$DNSTT_BINARY" ]]; then
        print_info "dnstt-server binary already exists"
        if ! confirm "Re-download latest version?"; then
            print_ok "Keeping existing binary"
        else
            download_dnstt_binary || return 1
        fi
    else
        download_dnstt_binary || return 1
    fi

    generate_keys || return 1

    # ── Step 7: Mode-specific setup ───────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Mode Setup ($CONF_MODE)"

    if [[ "$CONF_MODE" == "socks" ]]; then
        install_dante_socks
        create_socks_user
    else
        print_ok "SSH mode: forwarding to localhost:$CONF_SSH_PORT"
        print_info "Make sure SSH is running on port $CONF_SSH_PORT"

        echo ""
        print_info "Create a restricted SSH user for tunnel access:"
        create_socks_user
    fi

    # ── Step 8: Configure and Start ───────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Configure & Start Service"

    setup_iptables
    save_config
    create_systemd_service

    print_info "Starting dnstt-server..."
    systemctl restart "$SYSTEMD_SERVICE"
    sleep 2

    if is_running; then
        print_ok "dnstt-server is RUNNING"
    else
        print_err "dnstt-server failed to start!"
        print_info "Check logs: journalctl -u $SYSTEMD_SERVICE -n 20"
        journalctl -u "$SYSTEMD_SERVICE" -n 10 --no-pager 2>/dev/null
    fi

    # ── Step 9: Summary ──────────────────────────────────────────────────────
    step=$((step + 1))
    show_summary

    print_ok "Setup complete! Run '$0' for the management menu."
}

# ─── Display Functions ────────────────────────────────────────────────────────

show_summary() {
    load_config 2>/dev/null

    print_header "Setup Complete — Connection Info" ""

    echo -e "  ${BOLD}Server Details${NC}"
    echo -e "    IP:         ${CYAN}${CONF_SERVER_IP:-$(detect_server_ip)}${NC}"
    echo -e "    Domain:     ${CYAN}${CONF_DOMAIN}${NC}"
    echo -e "    Mode:       ${CYAN}${CONF_MODE}${NC}"
    echo -e "    MTU:        ${CYAN}${CONF_MTU}${NC}"
    echo -e "    Public Key: ${CYAN}${CONF_PUBKEY}${NC}"

    if [[ -n "${CONF_SOCKS_USER:-}" ]]; then
        echo ""
        echo -e "  ${BOLD}Tunnel User${NC}"
        echo -e "    Username:   ${CYAN}${CONF_SOCKS_USER}${NC}"
        echo -e "    Password:   ${CYAN}${CONF_SOCKS_PASS}${NC}"
    fi

    echo ""
    print_line 60 "─"
    echo -e "  ${BOLD}${GREEN}Client Connection Commands (try in order):${NC}"
    print_line 60 "─"

    echo ""
    echo -e "  ${BOLD}1. DoH via Google ${GREEN}(RECOMMENDED — hardest to detect)${NC}"
    echo -e "  ${WHITE}dnstt-client -doh https://dns.google/dns-query \\${NC}"
    echo -e "  ${WHITE}  -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000${NC}"

    echo ""
    echo -e "  ${BOLD}2. DoH via Cloudflare${NC}"
    echo -e "  ${WHITE}dnstt-client -doh https://cloudflare-dns.com/dns-query \\${NC}"
    echo -e "  ${WHITE}  -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000${NC}"

    echo ""
    echo -e "  ${BOLD}3. DoH via Quad9${NC}"
    echo -e "  ${WHITE}dnstt-client -doh https://dns.quad9.net/dns-query \\${NC}"
    echo -e "  ${WHITE}  -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000${NC}"

    echo ""
    echo -e "  ${BOLD}4. DoT via Google${NC}"
    echo -e "  ${WHITE}dnstt-client -dot dns.google:853 \\${NC}"
    echo -e "  ${WHITE}  -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000${NC}"

    echo ""
    echo -e "  ${BOLD}5. UDP — old method ${YELLOW}(often blocked in Iran)${NC}"
    echo -e "  ${WHITE}dnstt-client -udp 8.8.8.8:53 \\${NC}"
    echo -e "  ${WHITE}  -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000${NC}"

    if [[ "$CONF_MODE" == "ssh" && -n "${CONF_SOCKS_USER:-}" ]]; then
        echo ""
        print_line 60 "─"
        echo -e "  ${BOLD}After connecting, create SSH SOCKS proxy:${NC}"
        echo -e "  ${WHITE}ssh -N -D 127.0.0.1:8000 -p 7000 ${CONF_SOCKS_USER}@127.0.0.1${NC}"
        echo -e "  Password: ${CYAN}${CONF_SOCKS_PASS}${NC}"
        echo ""
        echo -e "  Browser proxy: ${GREEN}SOCKS5 → 127.0.0.1:8000${NC}"
    else
        echo ""
        echo -e "  Browser proxy: ${GREEN}SOCKS5 → 127.0.0.1:7000${NC}"
    fi

    echo ""
    print_line 60 "─"
    echo -e "  ${BOLD}Public Key (save as server.pub on client):${NC}"
    echo -e "  ${CYAN}${CONF_PUBKEY}${NC}"

    echo ""
    print_line 60 "─"
    echo -e "  ${BOLD}Download client binary:${NC}"
    echo -e "  ${WHITE}https://dnstt.network${NC}"
    echo ""
    print_line 60 "─"

    # Shareable quick-connect for friends
    echo -e "  ${BOLD}${MAGENTA}Quick Share (copy & send to friend):${NC}"
    print_line 60 "─"
    echo ""
    echo -e "  ${DIM}# --- Copy everything below this line ---${NC}"
    echo ""
    echo "  1. Download dnstt-client: https://dnstt.network"
    echo "  2. Save public key as server.pub:"
    echo "     ${CONF_PUBKEY}"
    echo "  3. Run:"
    echo "     dnstt-client -doh https://dns.google/dns-query -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000"
    echo "  4. If Google fails, try:"
    echo "     dnstt-client -doh https://cloudflare-dns.com/dns-query -pubkey-file server.pub ${CONF_DOMAIN} 127.0.0.1:7000"

    if [[ "$CONF_MODE" == "ssh" && -n "${CONF_SOCKS_USER:-}" ]]; then
        echo "  5. SSH tunnel:"
        echo "     ssh -N -D 127.0.0.1:8000 -p 7000 ${CONF_SOCKS_USER}@127.0.0.1"
        echo "     Password: ${CONF_SOCKS_PASS}"
        echo "  6. Browser SOCKS5 proxy: 127.0.0.1:8000"
    else
        echo "  5. Browser SOCKS5 proxy: 127.0.0.1:7000"
    fi

    echo ""
    echo -e "  ${DIM}# --- End of share block ---${NC}"
    echo ""
}

show_status() {
    print_header "Service Status" ""

    # dnstt-server
    echo -e "  ${BOLD}dnstt-server:${NC}"
    if is_running; then
        echo -e "    Status: ${GREEN}● RUNNING${NC}"
    else
        echo -e "    Status: ${RED}● STOPPED${NC}"
    fi

    local pid
    pid=$(pgrep -f "dnstt-server" 2>/dev/null | head -1)
    if [[ -n "$pid" ]]; then
        echo -e "    PID:    $pid"
        local mem
        mem=$(ps -p "$pid" -o rss= 2>/dev/null | awk '{printf "%.1f MB", $1/1024}')
        echo -e "    Memory: $mem"
        local uptime_info
        uptime_info=$(ps -p "$pid" -o etime= 2>/dev/null | xargs)
        echo -e "    Uptime: $uptime_info"
    fi

    # Dante (if SOCKS mode)
    if [[ -f "$DANTE_CONF" ]]; then
        echo ""
        echo -e "  ${BOLD}Dante SOCKS proxy:${NC}"
        if systemctl is-active --quiet "$DANTE_SERVICE" 2>/dev/null; then
            echo -e "    Status: ${GREEN}● RUNNING${NC}"
        else
            echo -e "    Status: ${RED}● STOPPED${NC}"
        fi
    fi

    # Port 53
    echo ""
    echo -e "  ${BOLD}Port 53:${NC}"
    local port53
    port53=$(ss -ulnp 2>/dev/null | grep ':53 ' | head -3)
    if [[ -n "$port53" ]]; then
        echo -e "    ${GREEN}● Listening${NC}"
        echo "$port53" | while read -r line; do
            echo -e "    ${DIM}$line${NC}"
        done
    else
        echo -e "    ${YELLOW}● Not listening${NC} (iptables redirect may be active)"
    fi

    # Port 5300
    echo ""
    echo -e "  ${BOLD}Port $DNSTT_PORT (dnstt):${NC}"
    local port5300
    port5300=$(ss -ulnp 2>/dev/null | grep ":${DNSTT_PORT} " | head -3)
    if [[ -n "$port5300" ]]; then
        echo -e "    ${GREEN}● Listening${NC}"
    else
        echo -e "    ${RED}● Not listening${NC}"
    fi

    # iptables
    echo ""
    echo -e "  ${BOLD}iptables NAT rules:${NC}"
    local nat_rules
    nat_rules=$(iptables -t nat -L PREROUTING -n 2>/dev/null | grep -c "dpt:53")
    echo -e "    Port 53 redirects: $nat_rules"

    # Config
    if is_configured; then
        load_config
        echo ""
        echo -e "  ${BOLD}Configuration:${NC}"
        echo -e "    Domain:  ${CONF_DOMAIN}"
        echo -e "    Mode:    ${CONF_MODE}"
        echo -e "    MTU:     ${CONF_MTU}"
        echo -e "    IP:      ${CONF_SERVER_IP}"
    fi

    echo ""
}

show_config() {
    if ! is_configured; then
        print_err "No configuration found. Run setup first."
        return 1
    fi

    load_config
    show_summary
}

show_logs() {
    print_header "Service Logs" "Press Ctrl+C to exit"

    echo ""
    echo "  1) dnstt-server logs (live)"
    echo "  2) dnstt-server logs (last 50 lines)"
    echo "  3) Dante SOCKS proxy logs"
    echo "  4) All logs combined"
    echo "  0) Back"
    echo ""

    read -rp "  Choose [1]: " log_choice
    log_choice="${log_choice:-1}"

    case "$log_choice" in
        1)
            echo ""
            print_info "Showing live logs (Ctrl+C to stop)..."
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -f --no-pager
            ;;
        2)
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -n 50 --no-pager
            press_enter
            ;;
        3)
            echo ""
            if systemctl list-units --type=service 2>/dev/null | grep -q "$DANTE_SERVICE"; then
                journalctl -u "$DANTE_SERVICE" -n 50 --no-pager
            else
                print_warn "Dante service not found"
            fi
            press_enter
            ;;
        4)
            echo ""
            print_info "Showing live combined logs (Ctrl+C to stop)..."
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -u "$DANTE_SERVICE" -f --no-pager
            ;;
        0) return ;;
    esac
}

start_services() {
    print_section "Starting Services"

    if ! is_configured; then
        print_err "No configuration found. Run setup first."
        return 1
    fi

    systemctl start "$SYSTEMD_SERVICE"
    sleep 1

    if is_running; then
        print_ok "dnstt-server started"
    else
        print_err "dnstt-server failed to start"
        print_info "Check: journalctl -u $SYSTEMD_SERVICE -n 20"
    fi

    # Start Dante if SOCKS mode
    load_config
    if [[ "${CONF_MODE:-}" == "socks" ]]; then
        systemctl start "$DANTE_SERVICE" 2>/dev/null
        if systemctl is-active --quiet "$DANTE_SERVICE" 2>/dev/null; then
            print_ok "Dante SOCKS proxy started"
        fi
    fi

    press_enter
}

stop_services() {
    print_section "Stopping Services"

    systemctl stop "$SYSTEMD_SERVICE" 2>/dev/null
    if ! is_running; then
        print_ok "dnstt-server stopped"
    else
        print_err "dnstt-server may still be running"
    fi

    systemctl stop "$DANTE_SERVICE" 2>/dev/null
    print_ok "Dante SOCKS proxy stopped"

    press_enter
}

restart_services() {
    print_section "Restarting Services"

    systemctl restart "$SYSTEMD_SERVICE"
    sleep 2

    if is_running; then
        print_ok "dnstt-server restarted"
    else
        print_err "dnstt-server failed to start"
        journalctl -u "$SYSTEMD_SERVICE" -n 5 --no-pager 2>/dev/null
    fi

    load_config 2>/dev/null
    if [[ "${CONF_MODE:-}" == "socks" ]]; then
        systemctl restart "$DANTE_SERVICE" 2>/dev/null
        if systemctl is-active --quiet "$DANTE_SERVICE"; then
            print_ok "Dante restarted"
        fi
    fi

    press_enter
}

reconfigure() {
    print_header "Reconfigure" "Change settings without full reinstall"

    if ! is_configured; then
        print_warn "No existing config. Running full setup instead."
        run_setup
        return
    fi

    load_config

    echo ""
    echo "  What would you like to change?"
    echo ""
    echo "  1) MTU value          (current: ${CONF_MTU})"
    echo "  2) Tunnel mode        (current: ${CONF_MODE})"
    echo "  3) Domain             (current: ${CONF_DOMAIN})"
    echo "  4) Tunnel user/pass   (current: ${CONF_SOCKS_USER:-none})"
    echo "  5) Regenerate keys"
    echo "  6) Full re-setup"
    echo "  0) Back"
    echo ""

    read -rp "  Choose [0]: " reconf_choice

    case "$reconf_choice" in
        1)
            echo ""
            echo -e "  Current MTU: ${CYAN}${CONF_MTU}${NC}"
            echo -e "  ${GREEN}512${NC}=max compat | ${YELLOW}800${NC}=balanced | ${CYAN}1024${NC}=faster"
            read -rp "  New MTU [$CONF_MTU]: " new_mtu
            if [[ -n "$new_mtu" ]]; then
                CONF_MTU="$new_mtu"
                save_config
                create_systemd_service
                systemctl restart "$SYSTEMD_SERVICE"
                sleep 1
                if is_running; then
                    print_ok "MTU changed to $CONF_MTU and service restarted"
                else
                    print_err "Service failed to restart"
                fi
            fi
            ;;
        2)
            echo ""
            echo "  1) SOCKS proxy"
            echo "  2) SSH tunnel"
            read -rp "  New mode: " new_mode
            if [[ "$new_mode" == "1" ]]; then
                CONF_MODE="socks"
                install_dante_socks
            elif [[ "$new_mode" == "2" ]]; then
                CONF_MODE="ssh"
            fi
            save_config
            create_systemd_service
            systemctl restart "$SYSTEMD_SERVICE"
            print_ok "Mode changed to $CONF_MODE"
            ;;
        3)
            echo ""
            read -rp "  New domain [${CONF_DOMAIN}]: " new_domain
            if [[ -n "$new_domain" ]]; then
                CONF_DOMAIN="$new_domain"
                generate_keys
                save_config
                create_systemd_service
                systemctl restart "$SYSTEMD_SERVICE"
                print_ok "Domain changed. New keys generated."
            fi
            ;;
        4)
            create_socks_user
            save_config
            print_ok "User credentials updated"
            ;;
        5)
            generate_keys
            save_config
            create_systemd_service
            systemctl restart "$SYSTEMD_SERVICE"
            print_ok "Keys regenerated and service restarted"
            print_warn "Clients need the new public key!"
            ;;
        6)
            run_setup
            ;;
        0) return ;;
    esac

    press_enter
}

uninstall() {
    print_header "Uninstall" "Remove all DNS tunnel components"

    print_warn "This will remove:"
    echo "    - dnstt-server binary and service"
    echo "    - Configuration and keys"
    echo "    - iptables rules"
    echo "    - Dante SOCKS proxy (if installed)"
    echo ""

    if ! confirm "Are you sure?"; then
        return
    fi

    # Stop services
    systemctl stop "$SYSTEMD_SERVICE" 2>/dev/null
    systemctl disable "$SYSTEMD_SERVICE" 2>/dev/null
    systemctl stop "$DANTE_SERVICE" 2>/dev/null

    # Remove files
    rm -f "$SERVICE_FILE"
    rm -f "$DNSTT_BINARY"
    rm -rf "$CONFIG_DIR"
    systemctl daemon-reload

    # Remove iptables rules
    iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null
    iptables -t nat -D PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null

    # Remove user
    userdel "$DNSTT_USER" 2>/dev/null

    print_ok "Uninstall complete"
    print_warn "DNS records in your registrar must be removed manually"
    print_warn "To re-enable systemd-resolved:"
    print_dim "  chattr -i /etc/resolv.conf"
    print_dim "  rm /etc/resolv.conf && ln -s ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf"
    print_dim "  systemctl unmask systemd-resolved && systemctl enable --now systemd-resolved"

    press_enter
}

# ─── Main Menu ────────────────────────────────────────────────────────────────

show_menu() {
    clear 2>/dev/null || true

    # Status indicator
    local status_icon status_text
    if is_running; then
        status_icon="${GREEN}●${NC}"
        status_text="${GREEN}RUNNING${NC}"
    elif is_configured; then
        status_icon="${RED}●${NC}"
        status_text="${RED}STOPPED${NC}"
    else
        status_icon="${YELLOW}●${NC}"
        status_text="${YELLOW}NOT INSTALLED${NC}"
    fi

    echo ""
    echo -e "${CYAN}  ╔══════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}  ║     DNS Tunnel Server Manager  v${SCRIPT_VERSION}      ║${NC}"
    echo -e "${CYAN}  ║     Optimized for censored networks         ║${NC}"
    echo -e "${CYAN}  ╚══════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  Status: $status_icon $status_text"

    if is_configured; then
        load_config 2>/dev/null
        echo -e "  Domain: ${CYAN}${CONF_DOMAIN:-?}${NC}  MTU: ${CYAN}${CONF_MTU:-?}${NC}  Mode: ${CYAN}${CONF_MODE:-?}${NC}"
    fi

    echo ""
    print_line 50 "─"
    echo ""

    if ! is_configured; then
        echo -e "  ${BOLD}1)${NC}  Install & Setup          ${GREEN}← start here${NC}"
    else
        echo -e "  ${BOLD}1)${NC}  Install & Setup          (re-run wizard)"
    fi

    echo -e "  ${BOLD}2)${NC}  Show Status"
    echo -e "  ${BOLD}3)${NC}  Show Configuration       (connection info + share)"
    echo -e "  ${BOLD}4)${NC}  View Logs"
    echo ""
    echo -e "  ${BOLD}5)${NC}  Start Services"
    echo -e "  ${BOLD}6)${NC}  Stop Services"
    echo -e "  ${BOLD}7)${NC}  Restart Services"
    echo ""
    echo -e "  ${BOLD}8)${NC}  Reconfigure              (change MTU, mode, domain...)"
    echo -e "  ${BOLD}9)${NC}  Uninstall"
    echo ""
    echo -e "  ${BOLD}0)${NC}  Exit"
    echo ""
    print_line 50 "─"
}

main_menu() {
    while true; do
        show_menu
        read -rp "  Choose [0-9]: " choice
        echo ""

        case "$choice" in
            1) run_setup ;;
            2) show_status; press_enter ;;
            3) show_config; press_enter ;;
            4) show_logs ;;
            5) start_services ;;
            6) stop_services ;;
            7) restart_services ;;
            8) reconfigure ;;
            9) uninstall ;;
            0)
                echo -e "  ${DIM}Goodbye${NC}"
                echo ""
                exit 0
                ;;
            *)
                print_warn "Invalid option"
                sleep 1
                ;;
        esac
    done
}

# ─── Entry Point ──────────────────────────────────────────────────────────────

# Root check (except for --help)
if [[ "${1:-}" != "--help" && "${1:-}" != "-h" && $EUID -ne 0 ]]; then
    echo -e "${RED}Error:${NC} This script must be run as root"
    echo "  sudo bash $0"
    exit 1
fi

case "${1:-}" in
    setup|install)
        run_setup
        ;;
    status)
        if is_configured; then load_config; fi
        show_status
        ;;
    config|show)
        show_config
        ;;
    logs|log)
        show_logs
        ;;
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        restart_services
        ;;
    -h|--help)
        echo ""
        echo "  DNS Tunnel Server Manager v$SCRIPT_VERSION"
        echo ""
        echo "  Usage: sudo bash $0 [command]"
        echo ""
        echo "  Commands:"
        echo "    (none)     Interactive menu"
        echo "    setup      Run the setup wizard"
        echo "    status     Show service status"
        echo "    config     Show configuration and connection info"
        echo "    logs       View service logs"
        echo "    start      Start services"
        echo "    stop       Stop services"
        echo "    restart    Restart services"
        echo ""
        ;;
    *)
        main_menu
        ;;
esac
