#!/usr/bin/env bash
#
# DNS Tunnel Server Manager
# All-in-one setup, management, and monitoring for DNSTT DNS tunnels
# Optimized for heavily censored networks (DoH/DoT/UDP)
#
# Tested on: Ubuntu 20.04 / 22.04 / 24.04
#
# Usage:
#   sudo bash dns-tunnel-server.sh          # Interactive menu
#   sudo bash dns-tunnel-server.sh setup    # Run setup wizard directly
#   sudo bash dns-tunnel-server.sh status   # Quick status check
#

set -uo pipefail

# ─── Constants ────────────────────────────────────────────────────────────────

SCRIPT_VERSION="1.0.0"
SCRIPT_NAME="dns-tunnel-server"
DNSTT_BINARY="/usr/local/bin/dnstt-server"
DNSTT_CLIENT_URL="https://dnstt.network"
DNSTT_BASE_URL="https://dnstt.network"
CONFIG_DIR="/etc/dnstt"
CONFIG_FILE="$CONFIG_DIR/tunnel.conf"
SYSTEMD_SERVICE="dnstt-server"
SYSTEMD_DIR="/etc/systemd/system"
SERVICE_FILE="$SYSTEMD_DIR/${SYSTEMD_SERVICE}.service"
DANTE_SERVICE="danted"
DANTE_CONF="/etc/danted.conf"
DNSTT_USER="dnstt"
DNSTT_PORT="5300"
LOG_FILE="/var/log/dnstt-server.log"
FILE_SERVER_DIR="/var/www/dnstt-clients"
FILE_SERVER_PORT="8443"
FILE_SERVER_SERVICE="dnstt-fileserver"

# ─── Colors ───────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

# ─── Utility Functions ────────────────────────────────────────────────────────

print_line() {
    printf '%*s\n' "${1:-60}" '' | tr ' ' "${2:-─}"
}

print_header() {
    local width=60
    echo ""
    echo -e "${CYAN}"
    print_line $width "═"
    printf "  %s\n" "$1"
    if [[ -n "${2:-}" ]]; then
        printf "  ${DIM}%s${NC}${CYAN}\n" "$2"
    fi
    print_line $width "═"
    echo -e "${NC}"
}

print_section() {
    echo ""
    echo -e "  ${BOLD}${BLUE}▸ $1${NC}"
    print_line 60 "─"
}

print_ok() {
    echo -e "  ${GREEN}✓${NC} $1"
}

print_err() {
    echo -e "  ${RED}✗${NC} $1"
}

print_warn() {
    echo -e "  ${YELLOW}!${NC} $1"
}

print_info() {
    echo -e "  ${CYAN}ℹ${NC} $1"
}

print_dim() {
    echo -e "  ${DIM}$1${NC}"
}

press_enter() {
    echo ""
    read -rp "  Press Enter to continue..." _
}

confirm() {
    local msg="${1:-Continue?}"
    read -rp "  $msg [Y/n]: " ans
    [[ -z "$ans" || "$ans" =~ ^[Yy] ]]
}

# ─── Detection Functions ─────────────────────────────────────────────────────

detect_os() {
    if [[ ! -f /etc/os-release ]]; then
        print_err "Cannot detect OS"
        return 1
    fi
    . /etc/os-release
    echo "$ID"
}

detect_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)  echo "amd64" ;;
        aarch64|arm64) echo "arm64" ;;
        armv7l|armhf)  echo "arm" ;;
        i686|i386)     echo "386" ;;
        *)             echo "amd64" ;;
    esac
}

detect_server_ip() {
    local ip
    ip=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null) ||
    ip=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null) ||
    ip=$(curl -s --max-time 5 https://icanhazip.com 2>/dev/null) ||
    ip=$(hostname -I 2>/dev/null | awk '{print $1}') ||
    ip="(unknown)"
    echo "$ip"
}

detect_ssh_port() {
    local port
    port=$(ss -tlnp 2>/dev/null | grep sshd | head -1 | grep -oP ':\K[0-9]+' | head -1)
    echo "${port:-22}"
}

detect_main_interface() {
    ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1
}

is_installed() {
    [[ -f "$DNSTT_BINARY" ]]
}

is_configured() {
    [[ -f "$CONFIG_FILE" ]]
}

is_running() {
    systemctl is-active --quiet "$SYSTEMD_SERVICE" 2>/dev/null
}

get_config_value() {
    local key="$1"
    if [[ -f "$CONFIG_FILE" ]]; then
        grep "^${key}=" "$CONFIG_FILE" 2>/dev/null | cut -d'=' -f2-
    fi
}

# ─── Load Config ──────────────────────────────────────────────────────────────

load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        CONF_DOMAIN=$(get_config_value "DOMAIN")
        CONF_MTU=$(get_config_value "MTU")
        CONF_MODE=$(get_config_value "MODE")
        CONF_SSH_PORT=$(get_config_value "SSH_PORT")
        CONF_PUBKEY=$(get_config_value "PUBKEY")
        CONF_PRIVKEY_FILE=$(get_config_value "PRIVKEY_FILE")
        CONF_PUBKEY_FILE=$(get_config_value "PUBKEY_FILE")
        CONF_SERVER_IP=$(get_config_value "SERVER_IP")
        CONF_SOCKS_USER=$(get_config_value "SOCKS_USER")
        CONF_SOCKS_PASS=$(get_config_value "SOCKS_PASS")
        return 0
    fi
    return 1
}

save_config() {
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" << EOF
# DNS Tunnel Server Configuration
# Generated by $SCRIPT_NAME v$SCRIPT_VERSION
# $(date)
DOMAIN=$CONF_DOMAIN
MTU=$CONF_MTU
MODE=$CONF_MODE
SSH_PORT=$CONF_SSH_PORT
PUBKEY=$CONF_PUBKEY
PRIVKEY_FILE=$CONF_PRIVKEY_FILE
PUBKEY_FILE=$CONF_PUBKEY_FILE
SERVER_IP=$CONF_SERVER_IP
SOCKS_USER=${CONF_SOCKS_USER:-}
SOCKS_PASS=${CONF_SOCKS_PASS:-}
EOF
    chmod 600 "$CONFIG_FILE"
}

# ─── Installation Functions ───────────────────────────────────────────────────

install_dependencies() {
    print_section "Installing Dependencies"

    local packages=(curl wget iptables)
    local to_install=()

    for pkg in "${packages[@]}"; do
        if ! command -v "$pkg" &>/dev/null; then
            to_install+=("$pkg")
        fi
    done

    if [[ ${#to_install[@]} -gt 0 ]]; then
        print_info "Installing: ${to_install[*]}"
        apt-get update -qq >/dev/null 2>&1
        apt-get install -y -qq "${to_install[@]}" >/dev/null 2>&1
        print_ok "Dependencies installed"
    else
        print_ok "All dependencies present"
    fi
}

download_dnstt_binary() {
    print_section "Downloading DNSTT Server Binary"

    local arch
    arch=$(detect_arch)
    local binary_name="dnstt-server-linux-${arch}"
    local url="${DNSTT_BASE_URL}/${binary_name}"

    print_info "Architecture: $arch"
    print_info "Downloading from: $url"

    local tmp_file="/tmp/${binary_name}"
    if ! curl -fsSL --connect-timeout 30 "$url" -o "$tmp_file"; then
        print_err "Failed to download dnstt-server"
        print_info "Try manually: curl -fsSL $url -o $DNSTT_BINARY"
        return 1
    fi

    chmod +x "$tmp_file"
    mv "$tmp_file" "$DNSTT_BINARY"
    print_ok "Binary installed: $DNSTT_BINARY"

    # Verify
    if "$DNSTT_BINARY" -h >/dev/null 2>&1 || [[ -x "$DNSTT_BINARY" ]]; then
        print_ok "Binary is executable"
    else
        print_err "Binary may not be working"
    fi
}

create_system_user() {
    if id "$DNSTT_USER" &>/dev/null; then
        print_ok "System user '$DNSTT_USER' already exists"
        return 0
    fi
    useradd -r -s /usr/sbin/nologin -d /nonexistent "$DNSTT_USER" 2>/dev/null
    print_ok "Created system user: $DNSTT_USER"
}

generate_keys() {
    print_section "Generating Encryption Keys"

    local domain_file
    domain_file=$(echo "$CONF_DOMAIN" | tr '.' '_')
    CONF_PRIVKEY_FILE="${CONFIG_DIR}/${domain_file}_server.key"
    CONF_PUBKEY_FILE="${CONFIG_DIR}/${domain_file}_server.pub"

    mkdir -p "$CONFIG_DIR"

    # Check for existing keys
    if [[ -f "$CONF_PRIVKEY_FILE" && -f "$CONF_PUBKEY_FILE" ]]; then
        print_info "Keys already exist for this domain"
        if confirm "Reuse existing keys?"; then
            CONF_PUBKEY=$(cat "$CONF_PUBKEY_FILE")
            print_ok "Reusing keys: $CONF_PUBKEY_FILE"
            return 0
        fi
    fi

    # Generate new keys
    print_info "Generating Curve25519 key pair..."
    "$DNSTT_BINARY" -gen-key -privkey-file "$CONF_PRIVKEY_FILE" -pubkey-file "$CONF_PUBKEY_FILE" 2>/dev/null

    if [[ ! -f "$CONF_PUBKEY_FILE" ]]; then
        print_err "Key generation failed"
        return 1
    fi

    CONF_PUBKEY=$(cat "$CONF_PUBKEY_FILE")
    chown "$DNSTT_USER":"$DNSTT_USER" "$CONF_PRIVKEY_FILE" 2>/dev/null
    chmod 600 "$CONF_PRIVKEY_FILE"

    print_ok "Private key: $CONF_PRIVKEY_FILE"
    print_ok "Public key:  $CONF_PUBKEY_FILE"
    print_info "Public key value: ${CYAN}$CONF_PUBKEY${NC}"
}

setup_iptables() {
    print_section "Configuring Firewall (iptables)"

    # Redirect port 53 to dnstt port
    local rules_needed=false

    if ! iptables -t nat -C PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null; then
        iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT"
        rules_needed=true
    fi
    if ! iptables -t nat -C PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null; then
        iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT"
        rules_needed=true
    fi

    # Allow port 53 in INPUT
    if ! iptables -C INPUT -p udp --dport 53 -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p udp --dport 53 -j ACCEPT
    fi
    if ! iptables -C INPUT -p tcp --dport 53 -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p tcp --dport 53 -j ACCEPT
    fi

    # Also allow the dnstt port directly
    if ! iptables -C INPUT -p udp --dport "$DNSTT_PORT" -j ACCEPT 2>/dev/null; then
        iptables -I INPUT -p udp --dport "$DNSTT_PORT" -j ACCEPT
    fi

    # UFW rules
    if command -v ufw &>/dev/null; then
        ufw allow 53/udp >/dev/null 2>&1
        ufw allow 53/tcp >/dev/null 2>&1
        ufw allow "$DNSTT_PORT"/udp >/dev/null 2>&1
        print_ok "UFW rules added for port 53 and $DNSTT_PORT"
    fi

    # Save iptables rules persistently
    if command -v netfilter-persistent &>/dev/null; then
        netfilter-persistent save >/dev/null 2>&1
    elif [[ -f /etc/iptables/rules.v4 ]]; then
        iptables-save > /etc/iptables/rules.v4 2>/dev/null
    fi

    print_ok "iptables rules configured (53 → $DNSTT_PORT)"
}

free_port_53() {
    print_section "Freeing Port 53"

    local port53_user
    port53_user=$(ss -ulnp 2>/dev/null | grep ':53 ' | head -1)

    if [[ -z "$port53_user" ]]; then
        print_ok "Port 53 is free"
        return 0
    fi

    print_warn "Port 53 is in use:"
    print_dim "$port53_user"

    # Check if it's systemd-resolved
    if echo "$port53_user" | grep -q "systemd-resolve\|resolved"; then
        print_info "systemd-resolved is using port 53. Disabling..."

        systemctl stop systemd-resolved.socket systemd-resolved.service 2>/dev/null
        systemctl disable systemd-resolved.socket systemd-resolved.service 2>/dev/null
        systemctl mask systemd-resolved.socket systemd-resolved.service 2>/dev/null

        # Fix resolv.conf
        chattr -i /etc/resolv.conf 2>/dev/null
        rm -f /etc/resolv.conf
        cat > /etc/resolv.conf << 'EOF'
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 9.9.9.9
EOF
        chattr +i /etc/resolv.conf 2>/dev/null

        print_ok "systemd-resolved disabled"
        print_ok "DNS set to 8.8.8.8, 1.1.1.1, 9.9.9.9"
    else
        print_warn "Unknown service on port 53. You may need to stop it manually."
        print_dim "Run: ss -ulnp | grep ':53 '"
        if ! confirm "Continue anyway?"; then
            return 1
        fi
    fi

    # Verify
    sleep 1
    if ss -ulnp 2>/dev/null | grep -q ':53 '; then
        print_err "Port 53 still in use!"
        pkill -9 systemd-resolve 2>/dev/null
        sleep 1
        if ss -ulnp 2>/dev/null | grep -q ':53 '; then
            print_err "Cannot free port 53. Please fix manually."
            return 1
        fi
    fi

    print_ok "Port 53 is now free"
}

install_dante_socks() {
    print_section "Installing Dante SOCKS5 Proxy"

    if command -v danted &>/dev/null; then
        print_ok "Dante already installed"
    else
        print_info "Installing dante-server..."
        apt-get install -y -qq dante-server >/dev/null 2>&1
        if ! command -v danted &>/dev/null; then
            print_err "Failed to install dante-server"
            print_info "Trying alternative: apt install dante-server"
            apt-get install -y dante-server 2>&1
        fi
    fi

    local iface
    iface=$(detect_main_interface)

    cat > "$DANTE_CONF" << EOF
# Dante SOCKS5 proxy for DNSTT tunnel
logoutput: syslog

internal: 127.0.0.1 port = 1080

external: $iface

socksmethod: username
clientmethod: none

user.privileged: root
user.notprivileged: nobody

client pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
    log: error
}

socks pass {
    from: 127.0.0.1/32 to: 0.0.0.0/0
    command: bind connect udpassociate
    log: error
    socksmethod: username
}
EOF

    systemctl enable "$DANTE_SERVICE" >/dev/null 2>&1
    systemctl restart "$DANTE_SERVICE" >/dev/null 2>&1

    if systemctl is-active --quiet "$DANTE_SERVICE"; then
        print_ok "Dante SOCKS5 running on 127.0.0.1:1080"
    else
        print_warn "Dante may not have started. Check: systemctl status danted"
    fi
}

create_socks_user() {
    print_section "Creating SOCKS Tunnel User"

    local default_user="tunnel"
    read -rp "  Username [$default_user]: " CONF_SOCKS_USER
    CONF_SOCKS_USER="${CONF_SOCKS_USER:-$default_user}"

    # Generate random password
    local rand_pass
    rand_pass=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 12)
    read -rp "  Password [$rand_pass]: " CONF_SOCKS_PASS
    CONF_SOCKS_PASS="${CONF_SOCKS_PASS:-$rand_pass}"

    # Create or update user
    if id "$CONF_SOCKS_USER" &>/dev/null; then
        print_info "User '$CONF_SOCKS_USER' exists, updating password..."
    else
        useradd -r -s /usr/sbin/nologin "$CONF_SOCKS_USER" 2>/dev/null ||
        useradd -r -s /bin/false "$CONF_SOCKS_USER" 2>/dev/null
    fi

    echo "${CONF_SOCKS_USER}:${CONF_SOCKS_PASS}" | chpasswd

    print_ok "User: $CONF_SOCKS_USER"
    print_ok "Pass: $CONF_SOCKS_PASS"
}

create_systemd_service() {
    print_section "Creating Systemd Service"

    local listen_addr="127.0.0.1:${DNSTT_PORT}"
    local forward_addr=""

    if [[ "$CONF_MODE" == "socks" ]]; then
        forward_addr="127.0.0.1:1080"
    else
        forward_addr="127.0.0.1:${CONF_SSH_PORT}"
    fi

    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=DNSTT DNS Tunnel Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$DNSTT_USER
Group=$DNSTT_USER
ExecStart=$DNSTT_BINARY \\
    -udp $listen_addr \\
    -privkey-file $CONF_PRIVKEY_FILE \\
    -mtu $CONF_MTU \\
    $CONF_DOMAIN \\
    $forward_addr
Restart=always
RestartSec=5
LimitNOFILE=65535

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadOnlyPaths=/
ReadWritePaths=/var/log
PrivateTmp=yes

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=dnstt-server

[Install]
WantedBy=multi-user.target
EOF

    # dnstt user needs read access to private key
    chown "$DNSTT_USER":"$DNSTT_USER" "$CONF_PRIVKEY_FILE" 2>/dev/null

    systemctl daemon-reload
    systemctl enable "$SYSTEMD_SERVICE" >/dev/null 2>&1

    print_ok "Service created: $SERVICE_FILE"
    print_ok "Forwarding to: $forward_addr"
}

# ─── Setup Wizard ─────────────────────────────────────────────────────────────

run_setup() {
    print_header "DNS Tunnel Server Setup Wizard" "Step-by-step guided installation"

    local total_steps=9
    local step=0

    # ── Step 1: Pre-flight ────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Pre-flight Checks"

    # Root check
    if [[ $EUID -ne 0 ]]; then
        print_err "Must run as root (sudo)"
        exit 1
    fi
    print_ok "Running as root"

    # OS check
    local os
    os=$(detect_os)
    if [[ "$os" != "ubuntu" && "$os" != "debian" ]]; then
        print_warn "OS '$os' detected. This script is tested on Ubuntu/Debian."
        if ! confirm "Continue anyway?"; then exit 0; fi
    else
        print_ok "OS: $os"
    fi

    # Detect IP
    CONF_SERVER_IP=$(detect_server_ip)
    print_ok "Server IP: $CONF_SERVER_IP"

    # Detect SSH
    CONF_SSH_PORT=$(detect_ssh_port)
    print_ok "SSH port: $CONF_SSH_PORT"

    # ── Step 2: Domain ────────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Domain Configuration"

    echo ""
    print_info "Enter the tunnel subdomain (not the base domain)"
    print_info "Example: ${CYAN}t.example.com${NC}"
    print_dim "You need an NS record pointing this subdomain to your server"
    echo ""

    local existing_domain=""
    if is_configured; then
        load_config
        existing_domain="$CONF_DOMAIN"
        print_info "Current domain: $existing_domain"
    fi

    read -rp "  Tunnel domain [${existing_domain:-t.example.com}]: " CONF_DOMAIN
    CONF_DOMAIN="${CONF_DOMAIN:-${existing_domain:-t.example.com}}"

    # Strip whitespace, protocol prefixes
    CONF_DOMAIN=$(echo "$CONF_DOMAIN" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s|^https\?://||;s|/$||')
    print_ok "Domain: $CONF_DOMAIN"

    # ── Step 3: DNS Records ───────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — DNS Records"

    local base_domain tunnel_sub ns_hostname
    # Extract parts
    base_domain=$(echo "$CONF_DOMAIN" | rev | cut -d. -f1-2 | rev)
    tunnel_sub=$(echo "$CONF_DOMAIN" | sed "s/\.$base_domain$//")
    ns_hostname="ns.$base_domain"

    echo ""
    echo -e "  ${BOLD}Create these DNS records in your registrar/Cloudflare:${NC}"
    echo ""
    echo -e "  ┌────────┬──────────────────────┬───────────────────────────┐"
    echo -e "  │ ${BOLD}Type${NC}   │ ${BOLD}Name${NC}                 │ ${BOLD}Value${NC}                     │"
    echo -e "  ├────────┼──────────────────────┼───────────────────────────┤"
    printf "  │ A      │ %-20s │ %-25s │\n" "ns" "$CONF_SERVER_IP"
    printf "  │ NS     │ %-20s │ %-25s │\n" "$tunnel_sub" "$ns_hostname"
    echo -e "  └────────┴──────────────────────┴───────────────────────────┘"
    echo ""
    print_warn "A record proxy must be OFF (grey cloud) if using Cloudflare"
    print_info "Wait 5-10 min for DNS propagation after creating records"
    echo ""

    if ! confirm "Have you created these DNS records?"; then
        print_warn "Create the records first, then re-run this setup"
        exit 0
    fi

    # ── Step 4: Tunnel Mode ───────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Tunnel Mode"

    echo ""
    echo -e "  ${BOLD}1)${NC} SOCKS proxy mode"
    print_dim "   Anyone with the domain + key can connect"
    print_dim "   Simpler setup, no passwords needed"
    echo ""
    echo -e "  ${BOLD}2)${NC} SSH tunnel mode"
    print_dim "   Requires username + password"
    print_dim "   Better access control, per-user auth"
    print_dim "   Compatible with mobile apps"
    echo ""

    read -rp "  Choose mode [1]: " mode_choice
    mode_choice="${mode_choice:-1}"

    if [[ "$mode_choice" == "2" ]]; then
        CONF_MODE="ssh"
        print_ok "Mode: SSH tunnel"
    else
        CONF_MODE="socks"
        print_ok "Mode: SOCKS proxy"
    fi

    # ── Step 5: MTU ───────────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — MTU Configuration"

    echo ""
    echo -e "  ${BOLD}MTU recommendations for censored networks:${NC}"
    echo ""
    echo -e "    ${GREEN}512${NC}  — Maximum compatibility (heavy censorship)"
    echo -e "    ${YELLOW}800${NC}  — Balanced"
    echo -e "    ${CYAN}1024${NC} — Faster, moderate censorship"
    echo -e "    1232 — Default (may not work under heavy filtering)"
    echo ""

    read -rp "  MTU [512]: " CONF_MTU
    CONF_MTU="${CONF_MTU:-512}"

    # Validate
    if [[ "$CONF_MTU" -lt 200 || "$CONF_MTU" -gt 1400 ]] 2>/dev/null; then
        print_warn "MTU must be 200-1400. Using 512."
        CONF_MTU=512
    fi
    print_ok "MTU: $CONF_MTU"

    # ── Step 6: Install ──────────────────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Installing Components"

    install_dependencies
    free_port_53
    create_system_user

    if [[ -f "$DNSTT_BINARY" ]]; then
        print_info "dnstt-server binary already exists"
        if ! confirm "Re-download latest version?"; then
            print_ok "Keeping existing binary"
        else
            download_dnstt_binary || return 1
        fi
    else
        download_dnstt_binary || return 1
    fi

    generate_keys || return 1

    # ── Step 7: Mode-specific setup ───────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Mode Setup ($CONF_MODE)"

    if [[ "$CONF_MODE" == "socks" ]]; then
        install_dante_socks
        create_socks_user
    else
        print_ok "SSH mode: forwarding to localhost:$CONF_SSH_PORT"
        print_info "Make sure SSH is running on port $CONF_SSH_PORT"

        echo ""
        print_info "Create a restricted SSH user for tunnel access:"
        create_socks_user
    fi

    # ── Step 8: Configure and Start ───────────────────────────────────────────
    step=$((step + 1))
    print_section "Step $step/$total_steps — Configure & Start Service"

    setup_iptables
    save_config
    create_systemd_service

    print_info "Starting dnstt-server..."
    systemctl restart "$SYSTEMD_SERVICE"
    sleep 2

    if is_running; then
        print_ok "dnstt-server is RUNNING"
    else
        print_err "dnstt-server failed to start!"
        print_info "Check logs: journalctl -u $SYSTEMD_SERVICE -n 20"
        journalctl -u "$SYSTEMD_SERVICE" -n 10 --no-pager 2>/dev/null
    fi

    # ── Step 9: Summary ──────────────────────────────────────────────────────
    step=$((step + 1))
    show_summary

    print_ok "Setup complete! Run '$0' for the management menu."
}

# ─── Display Functions ────────────────────────────────────────────────────────

show_summary() {
    load_config 2>/dev/null

    print_header "Setup Complete — Connection Info" ""

    echo -e "  ${BOLD}Server Details${NC}"
    echo -e "    IP:         ${CYAN}${CONF_SERVER_IP:-$(detect_server_ip)}${NC}"
    echo -e "    Domain:     ${CYAN}${CONF_DOMAIN}${NC}"
    echo -e "    Mode:       ${CYAN}${CONF_MODE}${NC}"
    echo -e "    MTU:        ${CYAN}${CONF_MTU}${NC}"
    echo -e "    Public Key: ${CYAN}${CONF_PUBKEY}${NC}"

    if [[ -n "${CONF_SOCKS_USER:-}" ]]; then
        echo ""
        echo -e "  ${BOLD}Tunnel User${NC}"
        echo -e "    Username:   ${CYAN}${CONF_SOCKS_USER}${NC}"
        echo -e "    Password:   ${CYAN}${CONF_SOCKS_PASS}${NC}"
    fi

    # ── DNS resolvers (diverse list — different ISPs block different ones) ──
    local resolver_addrs=(
        "8.8.8.8:53"
        "8.8.4.4:53"
        "1.1.1.1:53"
        "1.0.0.1:53"
        "9.9.9.9:53"
        "149.112.112.112:53"
        "208.67.222.222:53"
        "208.67.220.220:53"
        "94.140.14.14:53"
        "94.140.15.15:53"
        "185.228.168.9:53"
        "185.228.169.9:53"
        "76.76.19.19:53"
        "76.76.2.0:53"
        "64.6.64.6:53"
        "64.6.65.6:53"
        "77.88.8.8:53"
        "77.88.8.1:53"
        "156.154.70.1:53"
        "156.154.71.1:53"
    )
    local resolver_names=(
        "Google-1"
        "Google-2"
        "Cloudflare-1"
        "Cloudflare-2"
        "Quad9-1"
        "Quad9-2"
        "OpenDNS-1"
        "OpenDNS-2"
        "AdGuard-1"
        "AdGuard-2"
        "CleanBrowsing-1"
        "CleanBrowsing-2"
        "ControlD-1"
        "ControlD-2"
        "Verisign-1"
        "Verisign-2"
        "Yandex-1"
        "Yandex-2"
        "Neustar-1"
        "Neustar-2"
    )

    local user="${CONF_SOCKS_USER:-}"
    local pass="${CONF_SOCKS_PASS:-}"
    local i

    # ── Generate dns:// config strings (HTTP Injector compatible) ──────────
    echo ""
    print_line 60 "═"
    echo -e "  ${BOLD}${GREEN}Config Strings for HTTP Injector (dns://)${NC}"
    echo -e "  ${DIM}Each uses a different DNS resolver — try until one works${NC}"
    echo -e "  ${DIM}Different ISPs block different resolvers${NC}"
    print_line 60 "═"

    for i in "${!resolver_addrs[@]}"; do
        local resolver="${resolver_addrs[$i]}"
        local rname="${resolver_names[$i]}"
        local config_json
        config_json=$(printf '{"ps":"%s","addr":"%s","ns":"%s","pubkey":"%s","user":"%s","pass":"%s"}' \
            "$rname" "$resolver" "$CONF_DOMAIN" "$CONF_PUBKEY" "$user" "$pass")
        local b64
        b64=$(echo -n "$config_json" | base64 -w0 2>/dev/null || echo -n "$config_json" | base64)

        echo ""
        echo -e "  ${BOLD}▸ ${rname}${NC} ${DIM}(${resolver})${NC}"
        echo -e "  ${WHITE}dns://${b64}${NC}"
    done

    # ── Generate slipnet:// config strings (SlipNet Android app) ───────────
    echo ""
    print_line 60 "═"
    echo -e "  ${BOLD}${GREEN}Config Strings for SlipNet (slipnet://)${NC}"
    echo -e "  ${DIM}Tap the link on Android → auto-imports${NC}"
    print_line 60 "═"

    local ssh_enabled="" ssh_port="22" ssh_host="127.0.0.1"
    if [[ -n "$user" && -n "$pass" ]]; then
        ssh_enabled="1"
    fi

    for i in "${!resolver_addrs[@]}"; do
        local resolver="${resolver_addrs[$i]}"
        local rname="${resolver_names[$i]}"
        # slipnet:// v16 pipe-delimited, 36 fields
        # field 5: resolvers, field 23: dnsTransport = "udp"
        local data="16|dnstt|${rname}|${CONF_DOMAIN}|${resolver}:0|0|5000|bbr|1080|127.0.0.1|0|${CONF_PUBKEY}|||${ssh_enabled}|${user}|${pass}|${ssh_port}|0|${ssh_host}|0||udp|password|||0|0|443|||0||0|0|"
        local slipnet_b64
        slipnet_b64=$(echo -n "$data" | base64 -w0 2>/dev/null || echo -n "$data" | base64)

        echo ""
        echo -e "  ${BOLD}▸ ${rname}${NC} ${DIM}(${resolver})${NC}"
        echo -e "  ${WHITE}slipnet://${slipnet_b64}${NC}"
    done

    # ── Manual settings (for any app) ──────────────────────────────────────
    echo ""
    print_line 60 "═"
    echo -e "  ${BOLD}Manual Settings (for any DNS tunnel app)${NC}"
    print_line 60 "═"
    echo ""
    echo -e "  Protocol:       ${CYAN}DNS Tunnel (DNSTT)${NC}"
    echo -e "  DNS Transport:  ${CYAN}UDP${NC}"
    echo -e "  Domain:         ${CYAN}${CONF_DOMAIN}${NC}"
    echo -e "  Public Key:     ${CYAN}${CONF_PUBKEY}${NC}"
    if [[ -n "$user" ]]; then
        echo -e "  SSH User:       ${CYAN}${user}${NC}"
        echo -e "  SSH Password:   ${CYAN}${pass}${NC}"
    fi
    echo ""
    echo -e "  ${YELLOW}Strategy: Send your friend 3-4 configs with different${NC}"
    echo -e "  ${YELLOW}resolvers. Each ISP blocks different ones.${NC}"
    echo ""
    echo -e "  ${DIM}Most likely to work: Google (8.8.8.8), Cloudflare (1.1.1.1)${NC}"
    echo -e "  ${DIM}Try if those fail: OpenDNS, Yandex, Verisign, Neustar${NC}"
    echo ""
}

show_status() {
    print_header "Service Status" ""

    # dnstt-server
    echo -e "  ${BOLD}dnstt-server:${NC}"
    if is_running; then
        echo -e "    Status: ${GREEN}● RUNNING${NC}"
    else
        echo -e "    Status: ${RED}● STOPPED${NC}"
    fi

    local pid
    pid=$(pgrep -f "dnstt-server" 2>/dev/null | head -1)
    if [[ -n "$pid" ]]; then
        echo -e "    PID:    $pid"
        local mem
        mem=$(ps -p "$pid" -o rss= 2>/dev/null | awk '{printf "%.1f MB", $1/1024}')
        echo -e "    Memory: $mem"
        local uptime_info
        uptime_info=$(ps -p "$pid" -o etime= 2>/dev/null | xargs)
        echo -e "    Uptime: $uptime_info"
    fi

    # Dante (if SOCKS mode)
    if [[ -f "$DANTE_CONF" ]]; then
        echo ""
        echo -e "  ${BOLD}Dante SOCKS proxy:${NC}"
        if systemctl is-active --quiet "$DANTE_SERVICE" 2>/dev/null; then
            echo -e "    Status: ${GREEN}● RUNNING${NC}"
        else
            echo -e "    Status: ${RED}● STOPPED${NC}"
        fi
    fi

    # Port 53
    echo ""
    echo -e "  ${BOLD}Port 53:${NC}"
    local port53
    port53=$(ss -ulnp 2>/dev/null | grep ':53 ' | head -3)
    if [[ -n "$port53" ]]; then
        echo -e "    ${GREEN}● Listening${NC}"
        echo "$port53" | while read -r line; do
            echo -e "    ${DIM}$line${NC}"
        done
    else
        echo -e "    ${YELLOW}● Not listening${NC} (iptables redirect may be active)"
    fi

    # Port 5300
    echo ""
    echo -e "  ${BOLD}Port $DNSTT_PORT (dnstt):${NC}"
    local port5300
    port5300=$(ss -ulnp 2>/dev/null | grep ":${DNSTT_PORT} " | head -3)
    if [[ -n "$port5300" ]]; then
        echo -e "    ${GREEN}● Listening${NC}"
    else
        echo -e "    ${RED}● Not listening${NC}"
    fi

    # iptables
    echo ""
    echo -e "  ${BOLD}iptables NAT rules:${NC}"
    local nat_rules
    nat_rules=$(iptables -t nat -L PREROUTING -n 2>/dev/null | grep -c "dpt:53")
    echo -e "    Port 53 redirects: $nat_rules"

    # Config
    if is_configured; then
        load_config
        echo ""
        echo -e "  ${BOLD}Configuration:${NC}"
        echo -e "    Domain:  ${CONF_DOMAIN}"
        echo -e "    Mode:    ${CONF_MODE}"
        echo -e "    MTU:     ${CONF_MTU}"
        echo -e "    IP:      ${CONF_SERVER_IP}"
    fi

    echo ""
}

show_config() {
    if ! is_configured; then
        print_err "No configuration found. Run setup first."
        return 1
    fi

    load_config
    show_summary
}

show_logs() {
    print_header "Service Logs" "Press Ctrl+C to exit"

    echo ""
    echo "  1) dnstt-server logs (live)"
    echo "  2) dnstt-server logs (last 50 lines)"
    echo "  3) Dante SOCKS proxy logs"
    echo "  4) All logs combined"
    echo "  0) Back"
    echo ""

    read -rp "  Choose [1]: " log_choice
    log_choice="${log_choice:-1}"

    case "$log_choice" in
        1)
            echo ""
            print_info "Showing live logs (Ctrl+C to stop)..."
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -f --no-pager
            ;;
        2)
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -n 50 --no-pager
            press_enter
            ;;
        3)
            echo ""
            if systemctl list-units --type=service 2>/dev/null | grep -q "$DANTE_SERVICE"; then
                journalctl -u "$DANTE_SERVICE" -n 50 --no-pager
            else
                print_warn "Dante service not found"
            fi
            press_enter
            ;;
        4)
            echo ""
            print_info "Showing live combined logs (Ctrl+C to stop)..."
            echo ""
            journalctl -u "$SYSTEMD_SERVICE" -u "$DANTE_SERVICE" -f --no-pager
            ;;
        0) return ;;
    esac
}

start_services() {
    print_section "Starting Services"

    if ! is_configured; then
        print_err "No configuration found. Run setup first."
        return 1
    fi

    systemctl start "$SYSTEMD_SERVICE"
    sleep 1

    if is_running; then
        print_ok "dnstt-server started"
    else
        print_err "dnstt-server failed to start"
        print_info "Check: journalctl -u $SYSTEMD_SERVICE -n 20"
    fi

    # Start Dante if SOCKS mode
    load_config
    if [[ "${CONF_MODE:-}" == "socks" ]]; then
        systemctl start "$DANTE_SERVICE" 2>/dev/null
        if systemctl is-active --quiet "$DANTE_SERVICE" 2>/dev/null; then
            print_ok "Dante SOCKS proxy started"
        fi
    fi

    press_enter
}

stop_services() {
    print_section "Stopping Services"

    systemctl stop "$SYSTEMD_SERVICE" 2>/dev/null
    if ! is_running; then
        print_ok "dnstt-server stopped"
    else
        print_err "dnstt-server may still be running"
    fi

    systemctl stop "$DANTE_SERVICE" 2>/dev/null
    print_ok "Dante SOCKS proxy stopped"

    press_enter
}

restart_services() {
    print_section "Restarting Services"

    systemctl restart "$SYSTEMD_SERVICE"
    sleep 2

    if is_running; then
        print_ok "dnstt-server restarted"
    else
        print_err "dnstt-server failed to start"
        journalctl -u "$SYSTEMD_SERVICE" -n 5 --no-pager 2>/dev/null
    fi

    load_config 2>/dev/null
    if [[ "${CONF_MODE:-}" == "socks" ]]; then
        systemctl restart "$DANTE_SERVICE" 2>/dev/null
        if systemctl is-active --quiet "$DANTE_SERVICE"; then
            print_ok "Dante restarted"
        fi
    fi

    press_enter
}

reconfigure() {
    print_header "Reconfigure" "Change settings without full reinstall"

    if ! is_configured; then
        print_warn "No existing config. Running full setup instead."
        run_setup
        return
    fi

    load_config

    echo ""
    echo "  What would you like to change?"
    echo ""
    echo "  1) MTU value          (current: ${CONF_MTU})"
    echo "  2) Tunnel mode        (current: ${CONF_MODE})"
    echo "  3) Domain             (current: ${CONF_DOMAIN})"
    echo "  4) Tunnel user/pass   (current: ${CONF_SOCKS_USER:-none})"
    echo "  5) Regenerate keys"
    echo "  6) Full re-setup"
    echo "  0) Back"
    echo ""

    read -rp "  Choose [0]: " reconf_choice

    case "$reconf_choice" in
        1)
            echo ""
            echo -e "  Current MTU: ${CYAN}${CONF_MTU}${NC}"
            echo -e "  ${GREEN}512${NC}=max compat | ${YELLOW}800${NC}=balanced | ${CYAN}1024${NC}=faster"
            read -rp "  New MTU [$CONF_MTU]: " new_mtu
            if [[ -n "$new_mtu" ]]; then
                CONF_MTU="$new_mtu"
                save_config
                create_systemd_service
                systemctl restart "$SYSTEMD_SERVICE"
                sleep 1
                if is_running; then
                    print_ok "MTU changed to $CONF_MTU and service restarted"
                else
                    print_err "Service failed to restart"
                fi
            fi
            ;;
        2)
            echo ""
            echo "  1) SOCKS proxy"
            echo "  2) SSH tunnel"
            read -rp "  New mode: " new_mode
            if [[ "$new_mode" == "1" ]]; then
                CONF_MODE="socks"
                install_dante_socks
            elif [[ "$new_mode" == "2" ]]; then
                CONF_MODE="ssh"
            fi
            save_config
            create_systemd_service
            systemctl restart "$SYSTEMD_SERVICE"
            print_ok "Mode changed to $CONF_MODE"
            ;;
        3)
            echo ""
            read -rp "  New domain [${CONF_DOMAIN}]: " new_domain
            if [[ -n "$new_domain" ]]; then
                CONF_DOMAIN="$new_domain"
                generate_keys
                save_config
                create_systemd_service
                systemctl restart "$SYSTEMD_SERVICE"
                print_ok "Domain changed. New keys generated."
            fi
            ;;
        4)
            create_socks_user
            save_config
            print_ok "User credentials updated"
            ;;
        5)
            generate_keys
            save_config
            create_systemd_service
            systemctl restart "$SYSTEMD_SERVICE"
            print_ok "Keys regenerated and service restarted"
            print_warn "Clients need the new public key!"
            ;;
        6)
            run_setup
            ;;
        0) return ;;
    esac

    press_enter
}

uninstall() {
    print_header "Uninstall" "Remove all DNS tunnel components"

    print_warn "This will remove:"
    echo "    - dnstt-server binary and service"
    echo "    - Configuration and keys"
    echo "    - iptables rules"
    echo "    - Dante SOCKS proxy (if installed)"
    echo ""

    if ! confirm "Are you sure?"; then
        return
    fi

    # Stop services
    systemctl stop "$SYSTEMD_SERVICE" 2>/dev/null
    systemctl disable "$SYSTEMD_SERVICE" 2>/dev/null
    systemctl stop "$DANTE_SERVICE" 2>/dev/null

    # Remove files
    rm -f "$SERVICE_FILE"
    rm -f "$DNSTT_BINARY"
    rm -rf "$CONFIG_DIR"
    systemctl daemon-reload

    # Remove iptables rules
    iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null
    iptables -t nat -D PREROUTING -p tcp --dport 53 -j REDIRECT --to-port "$DNSTT_PORT" 2>/dev/null

    # Remove user
    userdel "$DNSTT_USER" 2>/dev/null

    print_ok "Uninstall complete"
    print_warn "DNS records in your registrar must be removed manually"
    print_warn "To re-enable systemd-resolved:"
    print_dim "  chattr -i /etc/resolv.conf"
    print_dim "  rm /etc/resolv.conf && ln -s ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf"
    print_dim "  systemctl unmask systemd-resolved && systemctl enable --now systemd-resolved"

    press_enter
}

# ─── Client File Server ───────────────────────────────────────────────────────

setup_file_server() {
    print_header "Client File Server" "Host client binaries on your VPS for people who can't access GitHub"

    if ! is_configured; then
        print_err "Run setup first (option 1)"
        press_enter
        return
    fi
    load_config

    local server_ip
    server_ip="${CONF_SERVER_IP:-$(detect_server_ip)}"

    echo ""
    echo -e "  ${BOLD}Problem:${NC} People in Iran can't access dnstt.network or GitHub"
    echo -e "  ${BOLD}Solution:${NC} Host client binaries directly on your VPS"
    echo ""
    echo -e "  This will:"
    echo -e "    1. Download dnstt-client for Windows, Linux, Mac, Android"
    echo -e "    2. Generate ready-to-use config + bootstrap scripts"
    echo -e "    3. Start a file server on port ${CYAN}${FILE_SERVER_PORT}${NC}"
    echo -e "    4. Your friends download from: ${CYAN}http://${server_ip}:${FILE_SERVER_PORT}/${NC}"
    echo ""

    read -rp "  File server port [$FILE_SERVER_PORT]: " custom_port
    FILE_SERVER_PORT="${custom_port:-$FILE_SERVER_PORT}"

    if ! confirm "Download client binaries and start file server?"; then
        return
    fi

    # Create directory
    mkdir -p "$FILE_SERVER_DIR"

    print_section "Downloading Client Binaries"

    local platforms=(
        "dnstt-client-linux-amd64"
        "dnstt-client-linux-arm64"
        "dnstt-client-windows-amd64.exe"
        "dnstt-client-darwin-amd64"
        "dnstt-client-darwin-arm64"
    )

    for binary in "${platforms[@]}"; do
        local url="${DNSTT_BASE_URL}/${binary}"
        local dest="${FILE_SERVER_DIR}/${binary}"
        if [[ -f "$dest" ]]; then
            print_ok "Already have: $binary"
        else
            print_info "Downloading $binary ..."
            if curl -fsSL --connect-timeout 30 "$url" -o "$dest" 2>/dev/null; then
                chmod +x "$dest"
                print_ok "Downloaded: $binary"
            else
                print_warn "Failed: $binary (may not exist for this platform)"
            fi
        fi
    done

    print_section "Generating Config Files"

    # server.pub
    cp "$CONF_PUBKEY_FILE" "$FILE_SERVER_DIR/server.pub" 2>/dev/null
    print_ok "server.pub"

    # config.json
    cat > "$FILE_SERVER_DIR/config.json" << CEOF
{
  "domain": "$CONF_DOMAIN",
  "pubkey": "$CONF_PUBKEY",
  "mtu": $CONF_MTU,
  "mode": "$CONF_MODE",
  "server_ip": "$server_ip",
  "ssh_user": "${CONF_SOCKS_USER:-}",
  "ssh_pass": "${CONF_SOCKS_PASS:-}",
  "resolvers": [
    "https://dns.google/dns-query",
    "https://cloudflare-dns.com/dns-query",
    "https://dns.quad9.net/dns-query"
  ]
}
CEOF
    print_ok "config.json"

    # Windows quick-connect.bat
    cat > "$FILE_SERVER_DIR/quick-connect.bat" << BEOF
@echo off
chcp 65001 >nul 2>&1
title DNS Tunnel
set "DOMAIN=$CONF_DOMAIN"
set "PUBKEY=$CONF_PUBKEY"
set "LOCAL_PORT=7000"
echo %PUBKEY%> "%~dp0server.pub"
echo.
echo  Domain: %DOMAIN%
echo  Trying DoH via Google...
echo.
echo  Once connected, set browser SOCKS5 proxy to 127.0.0.1:%LOCAL_PORT%
echo  Press Ctrl+C to disconnect.
echo.
dnstt-client-windows-amd64.exe -doh https://dns.google/dns-query -pubkey-file "%~dp0server.pub" %DOMAIN% 127.0.0.1:%LOCAL_PORT%
if %ERRORLEVEL% NEQ 0 (
  echo  Google failed. Trying Cloudflare...
  dnstt-client-windows-amd64.exe -doh https://cloudflare-dns.com/dns-query -pubkey-file "%~dp0server.pub" %DOMAIN% 127.0.0.1:%LOCAL_PORT%
)
pause
BEOF
    print_ok "quick-connect.bat"

    # Linux quick-connect.sh
    cat > "$FILE_SERVER_DIR/quick-connect.sh" << SEOF
#!/bin/bash
DOMAIN="$CONF_DOMAIN"
PUBKEY="$CONF_PUBKEY"
echo \"\ \$PUBKEY\" > server.pub
CLIENT="./dnstt-client-linux-\$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"
chmod +x "\$CLIENT" 2>/dev/null
echo "Connecting via DoH (Google)..."
echo "SOCKS5 proxy will be on 127.0.0.1:7000"
"\$CLIENT" -doh https://dns.google/dns-query -pubkey-file server.pub "\$DOMAIN" 127.0.0.1:7000 || \\
"\$CLIENT" -doh https://cloudflare-dns.com/dns-query -pubkey-file server.pub "\$DOMAIN" 127.0.0.1:7000
SEOF
    chmod +x "$FILE_SERVER_DIR/quick-connect.sh"
    print_ok "quick-connect.sh"

    # Instructions text (for messaging apps)
    cat > "$FILE_SERVER_DIR/README.txt" << IEOF
=== DNS Tunnel Connection Guide ===

Step 1: Download the client for your OS from this page
Step 2: Download server.pub from this page
Step 3: Put both files in the same folder
Step 4: Run this command:

  Windows:
    dnstt-client-windows-amd64.exe -doh https://dns.google/dns-query -pubkey-file server.pub $CONF_DOMAIN 127.0.0.1:7000

  Linux:
    chmod +x dnstt-client-linux-amd64
    ./dnstt-client-linux-amd64 -doh https://dns.google/dns-query -pubkey-file server.pub $CONF_DOMAIN 127.0.0.1:7000

  Mac (Intel):
    chmod +x dnstt-client-darwin-amd64
    ./dnstt-client-darwin-amd64 -doh https://dns.google/dns-query -pubkey-file server.pub $CONF_DOMAIN 127.0.0.1:7000

  Mac (Apple Silicon):
    chmod +x dnstt-client-darwin-arm64
    ./dnstt-client-darwin-arm64 -doh https://dns.google/dns-query -pubkey-file server.pub $CONF_DOMAIN 127.0.0.1:7000

Step 5: Set browser SOCKS5 proxy to: 127.0.0.1:7000

If Google DoH doesn't work, replace the URL with:
  https://cloudflare-dns.com/dns-query
  https://dns.quad9.net/dns-query
  https://dns.adguard-dns.com/dns-query
IEOF

    if [[ "$CONF_MODE" == "ssh" && -n "${CONF_SOCKS_USER:-}" ]]; then
        cat >> "$FILE_SERVER_DIR/README.txt" << IEOF2

SSH Tunnel (after connecting with dnstt-client):
  ssh -N -D 127.0.0.1:8000 -p 7000 ${CONF_SOCKS_USER}@127.0.0.1
  Password: ${CONF_SOCKS_PASS}
  Then set browser proxy to: 127.0.0.1:8000
IEOF2
    fi
    print_ok "README.txt"

    # index.html for the file server
    cat > "$FILE_SERVER_DIR/index.html" << 'HEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Files</title>
<style>
body{font-family:system-ui,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;background:#0d1117;color:#c9d1d9}
a{color:#58a6ff;text-decoration:none}a:hover{text-decoration:underline}
.f{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin:8px 0}
.f a{font-size:1.1em;font-weight:600}
.tag{display:inline-block;font-size:0.75em;padding:2px 8px;border-radius:12px;margin-left:8px}
.win{background:#1f3a1f;color:#7ee787}.lin{background:#1a2a3f;color:#79c0ff}.mac{background:#2a1f3a;color:#d2a8ff}
.cfg{background:#3a2a1f;color:#ffa657}
pre{background:#161b22;padding:12px;border-radius:6px;overflow-x:auto;font-size:0.9em;border:1px solid #30363d}
h1{border-bottom:1px solid #30363d;padding-bottom:12px}
h2{margin-top:24px;color:#8b949e}
</style>
</head>
<body>
HEOF

    cat >> "$FILE_SERVER_DIR/index.html" << HEOF2
<h1>DNS Tunnel Client Downloads</h1>
<p>Domain: <code>$CONF_DOMAIN</code> | Server: <code>$server_ip</code></p>

<h2>Step 1 — Download client for your OS</h2>
HEOF2

    # Add download links for each file that exists
    for f in "$FILE_SERVER_DIR"/dnstt-client-*; do
        [[ -f "$f" ]] || continue
        local fname
        fname=$(basename "$f")
        local size
        size=$(du -h "$f" | cut -f1)
        local tag=""
        [[ "$fname" == *windows* ]] && tag='<span class="tag win">Windows</span>'
        [[ "$fname" == *linux* ]]   && tag='<span class="tag lin">Linux</span>'
        [[ "$fname" == *darwin* ]]  && tag='<span class="tag mac">macOS</span>'
        echo "<div class=\"f\"><a href=\"$fname\">$fname</a> ${tag} <small>($size)</small></div>" >> "$FILE_SERVER_DIR/index.html"
    done

    cat >> "$FILE_SERVER_DIR/index.html" << HEOF3

<h2>Step 2 — Download config</h2>
<div class="f"><a href="server.pub">server.pub</a> <span class="tag cfg">Required</span></div>
<div class="f"><a href="quick-connect.bat">quick-connect.bat</a> <span class="tag win">Windows one-click</span></div>
<div class="f"><a href="quick-connect.sh">quick-connect.sh</a> <span class="tag lin">Linux one-click</span></div>
<div class="f"><a href="config.json">config.json</a> <span class="tag cfg">Full config</span></div>
<div class="f"><a href="README.txt">README.txt</a> <span class="tag cfg">Instructions</span></div>

<h2>Step 3 — Quick start</h2>
<p><strong>Windows:</strong> Download <code>dnstt-client-windows-amd64.exe</code> + <code>server.pub</code>, then run:</p>
<pre>dnstt-client-windows-amd64.exe -doh https://dns.google/dns-query -pubkey-file server.pub $CONF_DOMAIN 127.0.0.1:7000</pre>
<p>Or just download <code>dnstt-client-windows-amd64.exe</code> + <code>quick-connect.bat</code> and double-click the .bat file.</p>
<p><strong>Then set browser SOCKS5 proxy to:</strong> <code>127.0.0.1:7000</code></p>
HEOF3

    if [[ "$CONF_MODE" == "ssh" && -n "${CONF_SOCKS_USER:-}" ]]; then
        cat >> "$FILE_SERVER_DIR/index.html" << HEOF4
<h2>Step 4 — SSH tunnel (after connecting)</h2>
<pre>ssh -N -D 127.0.0.1:8000 -p 7000 ${CONF_SOCKS_USER}@127.0.0.1
Password: ${CONF_SOCKS_PASS}</pre>
<p>Then set browser proxy to <code>127.0.0.1:8000</code></p>
HEOF4
    fi

    echo "</body></html>" >> "$FILE_SERVER_DIR/index.html"
    print_ok "index.html (download page)"

    print_section "Starting File Server"

    # Generate self-signed cert for HTTPS
    local cert_file="$CONFIG_DIR/fileserver.pem"
    local key_file="$CONFIG_DIR/fileserver.key"
    if [[ ! -f "$cert_file" ]]; then
        openssl req -x509 -newkey rsa:2048 -keyout "$key_file" -out "$cert_file" \
            -days 3650 -nodes -subj "/CN=$server_ip" 2>/dev/null
        print_ok "Generated self-signed TLS certificate"
    fi

    # Create systemd service for file server
    cat > "$SYSTEMD_DIR/${FILE_SERVER_SERVICE}.service" << FEOF
[Unit]
Description=DNSTT Client File Server
After=network.target

[Service]
Type=simple
WorkingDirectory=$FILE_SERVER_DIR
ExecStart=/usr/bin/python3 -c "
import http.server, ssl, sys
handler = http.server.SimpleHTTPRequestHandler
httpd = http.server.HTTPServer(('0.0.0.0', $FILE_SERVER_PORT), handler)
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
try:
    ctx.load_cert_chain('$cert_file', '$key_file')
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    print(f'HTTPS file server on port $FILE_SERVER_PORT')
except Exception:
    print(f'HTTP file server on port $FILE_SERVER_PORT (no TLS)')
sys.stdout.flush()
httpd.serve_forever()
"
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
FEOF

    systemctl daemon-reload
    systemctl enable "$FILE_SERVER_SERVICE" >/dev/null 2>&1
    systemctl restart "$FILE_SERVER_SERVICE"
    sleep 2

    # Open firewall
    if command -v ufw &>/dev/null; then
        ufw allow "$FILE_SERVER_PORT"/tcp >/dev/null 2>&1
    fi
    iptables -I INPUT -p tcp --dport "$FILE_SERVER_PORT" -j ACCEPT 2>/dev/null

    if systemctl is-active --quiet "$FILE_SERVER_SERVICE"; then
        print_ok "File server is RUNNING"
    else
        print_err "File server failed to start"
        journalctl -u "$FILE_SERVER_SERVICE" -n 5 --no-pager 2>/dev/null
    fi

    # Show result
    echo ""
    echo -e "${GREEN}  ═══════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  FILE SERVER READY${NC}"
    echo -e "${GREEN}  ═══════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  Download page:  ${CYAN}https://${server_ip}:${FILE_SERVER_PORT}/${NC}"
    echo -e "  (or HTTP)       ${CYAN}http://${server_ip}:${FILE_SERVER_PORT}/${NC}"
    echo ""
    echo -e "  ${BOLD}Share this link with your friends in Iran.${NC}"
    echo -e "  They open it in a browser, download the files,"
    echo -e "  and follow the instructions on the page."
    echo ""
    echo -e "  ${YELLOW}If direct IP access is blocked too:${NC}"
    echo -e "  ${DIM}  Use the bootstrap script below — it's small enough${NC}"
    echo -e "  ${DIM}  to copy-paste in a text message.${NC}"
    echo ""
    print_line 55 "─"
    echo -e "  ${BOLD}${MAGENTA}BOOTSTRAP (copy-paste this entire block to friend):${NC}"
    print_line 55 "─"
    echo ""

    # Generate a tiny PowerShell bootstrap
    cat << PSEOF
  --- WINDOWS: Save as connect.ps1 and run with PowerShell ---

  \$d="$CONF_DOMAIN";\$k="$CONF_PUBKEY";\$s="$server_ip";\$p=$FILE_SERVER_PORT
  \$k|Out-File server.pub -Encoding ascii -NoNewline
  \$u="https://\${s}:\${p}/dnstt-client-windows-amd64.exe"
  [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12
  try{\$wc=New-Object Net.WebClient
  [Net.ServicePointManager]::ServerCertificateValidationCallback={\$true}
  \$wc.DownloadFile(\$u,"dnstt-client.exe");Write-Host"Downloaded client"}
  catch{Write-Host"Download failed - get dnstt-client manually"}
  .\\dnstt-client.exe -doh https://dns.google/dns-query -pubkey-file server.pub \$d 127.0.0.1:7000
PSEOF
    echo ""
    cat << SHEOF
  --- LINUX: Save as connect.sh and run with bash ---

  d="$CONF_DOMAIN";k="$CONF_PUBKEY";s="$server_ip";p=$FILE_SERVER_PORT
  echo "\$k">server.pub
  curl -kfsSL "https://\$s:\$p/dnstt-client-linux-amd64" -o dnstt-client && chmod +x dnstt-client \\
    || wget --no-check-certificate -q "https://\$s:\$p/dnstt-client-linux-amd64" -O dnstt-client && chmod +x dnstt-client
  ./dnstt-client -doh https://dns.google/dns-query -pubkey-file server.pub "\$d" 127.0.0.1:7000
SHEOF
    echo ""
    print_line 55 "─"
    echo ""
    echo -e "  ${BOLD}Pre-distribution tip:${NC} Download the files from"
    echo -e "  ${CYAN}https://${server_ip}:${FILE_SERVER_PORT}/${NC}"
    echo -e "  and share via USB/Bluetooth/Telegram BEFORE the next shutdown."
    echo ""

    press_enter
}

stop_file_server() {
    systemctl stop "$FILE_SERVER_SERVICE" 2>/dev/null
    systemctl disable "$FILE_SERVER_SERVICE" 2>/dev/null
    print_ok "File server stopped"
    press_enter
}

# ─── Main Menu ────────────────────────────────────────────────────────────────

show_menu() {
    clear 2>/dev/null || true

    # Status indicator
    local status_icon status_text
    if is_running; then
        status_icon="${GREEN}●${NC}"
        status_text="${GREEN}RUNNING${NC}"
    elif is_configured; then
        status_icon="${RED}●${NC}"
        status_text="${RED}STOPPED${NC}"
    else
        status_icon="${YELLOW}●${NC}"
        status_text="${YELLOW}NOT INSTALLED${NC}"
    fi

    echo ""
    echo -e "${CYAN}  ╔══════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}  ║     DNS Tunnel Server Manager  v${SCRIPT_VERSION}      ║${NC}"
    echo -e "${CYAN}  ║     Optimized for censored networks         ║${NC}"
    echo -e "${CYAN}  ╚══════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  Status: $status_icon $status_text"

    if is_configured; then
        load_config 2>/dev/null
        echo -e "  Domain: ${CYAN}${CONF_DOMAIN:-?}${NC}  MTU: ${CYAN}${CONF_MTU:-?}${NC}  Mode: ${CYAN}${CONF_MODE:-?}${NC}"
    fi

    echo ""
    print_line 50 "─"
    echo ""

    if ! is_configured; then
        echo -e "  ${BOLD}1)${NC}  Install & Setup          ${GREEN}← start here${NC}"
    else
        echo -e "  ${BOLD}1)${NC}  Install & Setup          (re-run wizard)"
    fi

    echo -e "  ${BOLD}2)${NC}  Show Status"
    echo -e "  ${BOLD}3)${NC}  Show Configuration       (connection info + share)"
    echo -e "  ${BOLD}4)${NC}  View Logs"
    echo ""
    echo -e "  ${BOLD}5)${NC}  Start Services"
    echo -e "  ${BOLD}6)${NC}  Stop Services"
    echo -e "  ${BOLD}7)${NC}  Restart Services"
    echo ""
    echo -e "  ${BOLD}8)${NC}  Reconfigure              (change MTU, mode, domain...)"
    echo ""
    echo -e "  ${BOLD}10)${NC} Host Client Files        ${YELLOW}(for friends who can't download)${NC}"
    echo -e "  ${BOLD}11)${NC} Stop File Server"
    echo ""
    echo -e "  ${BOLD}9)${NC}  Uninstall"
    echo -e "  ${BOLD}0)${NC}  Exit"
    echo ""
    print_line 50 "─"
}

main_menu() {
    while true; do
        show_menu
        read -rp "  Choose [0-11]: " choice
        echo ""

        case "$choice" in
            1) run_setup ;;
            2) show_status; press_enter ;;
            3) show_config; press_enter ;;
            4) show_logs ;;
            5) start_services ;;
            6) stop_services ;;
            7) restart_services ;;
            8) reconfigure ;;
            10) setup_file_server ;;
            11) stop_file_server ;;
            9) uninstall ;;
            0)
                echo -e "  ${DIM}Goodbye${NC}"
                echo ""
                exit 0
                ;;
            *)
                print_warn "Invalid option"
                sleep 1
                ;;
        esac
    done
}

# ─── Entry Point ──────────────────────────────────────────────────────────────

# Root check (except for --help)
if [[ "${1:-}" != "--help" && "${1:-}" != "-h" && $EUID -ne 0 ]]; then
    echo -e "${RED}Error:${NC} This script must be run as root"
    echo "  sudo bash $0"
    exit 1
fi

case "${1:-}" in
    setup|install)
        run_setup
        ;;
    status)
        if is_configured; then load_config; fi
        show_status
        ;;
    config|show)
        show_config
        ;;
    logs|log)
        show_logs
        ;;
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        restart_services
        ;;
    serve|files)
        setup_file_server
        ;;
    -h|--help)
        echo ""
        echo "  DNS Tunnel Server Manager v$SCRIPT_VERSION"
        echo ""
        echo "  Usage: sudo bash $0 [command]"
        echo ""
        echo "  Commands:"
        echo "    (none)     Interactive menu"
        echo "    setup      Run the setup wizard"
        echo "    status     Show service status"
        echo "    config     Show configuration and connection info"
        echo "    logs       View service logs"
        echo "    start      Start services"
        echo "    stop       Stop services"
        echo "    restart    Restart services"
        echo "    serve      Start client file server"
        echo ""
        ;;
    *)
        main_menu
        ;;
esac
